In [1]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline

In [57]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")
sample_submit=pd.read_csv("Sample_Submission_Tm9Lura.csv")

In [58]:
train.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [59]:
train.shape

(550068, 12)

In [60]:
test.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
2,1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
3,1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0

In [61]:
test.shape

(233599, 11)

In [62]:
train.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [63]:
test.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3'],
      dtype='object')

In [64]:
train.columns.difference(test.columns)

Index(['Purchase'], dtype='object')

In [65]:
train["Source"]='train'
test["Source"]='test'

In [66]:
dataf=pd.concat([train,test],axis=0,sort=False)

In [67]:
dataf.sort_index().head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Source
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370.0,train
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN,NaN,test
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200.0,train
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN,NaN,test
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422.0,train

In [68]:
dataf.reset_index(inplace=True,drop=True)

In [69]:
dataf.sort_index().head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Source
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370.0,train
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200.0,train
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422.0,train
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057.0,train
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969.0,train

In [70]:
dataf.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            245982
Product_Category_3            545809
Purchase                      233599
Source                             0
dtype: int64

In [71]:
dataf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783667 entries, 0 to 783666
Data columns (total 13 columns):
User_ID                       783667 non-null int64
Product_ID                    783667 non-null object
Gender                        783667 non-null object
Age                           783667 non-null object
Occupation                    783667 non-null int64
City_Category                 783667 non-null object
Stay_In_Current_City_Years    783667 non-null object
Marital_Status                783667 non-null int64
Product_Category_1            783667 non-null int64
Product_Category_2            537685 non-null float64
Product_Category_3            237858 non-null float64
Purchase                      550068 non-null float64
Source                        783667 non-null object
dtypes: float64(3), int64(4), object(6)
memory usage: 77.7+ MB

In [72]:
dataf.shape

(783667, 13)

In [73]:
dataf.nunique()

User_ID                        5891
Product_ID                     3677
Gender                            2
Age                               7
Occupation                       21
City_Category                     3
Stay_In_Current_City_Years        5
Marital_Status                    2
Product_Category_1               20
Product_Category_2               17
Product_Category_3               15
Purchase                      18105
Source                            2
dtype: int64

In [74]:
dataf.duplicated().sum()

0

In [37]:
import pandas_profiling

C:\ProgramData\Anaconda3\lib\site-packages\pandas_profiling\plot.py:15: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2666, in run_cell
    self.events.trigger('post_run_cell', result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\events.py", line 88, in trigger
    func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\pylab\backend_inline.py", line 160, in configure_once
    activate_matplotlib(backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 311, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 231, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1410, in use
    reload(sys.modules['matplotlib.backends'])
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use(BACKEND)

In [38]:
pandas_profiling.ProfileReport(dataf)

In [75]:
dataf[(dataf['Product_ID']=='P00285442') & (dataf['Product_Category_3'].notna())]

Empty DataFrame
Columns: [User_ID, Product_ID, Gender, Age, Occupation, City_Category, Stay_In_Current_City_Years, Marital_Status, Product_Category_1, Product_Category_2, Product_Category_3, Purchase, Source]
Index: []

In [81]:
dataf['Product_Category_3'].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [51]:
dataf['Product_Category_3'].isna().value_counts()

True     545809
False    237858
Name: Product_Category_3, dtype: int64

In [82]:
dataf.loc[dataf['Product_Category_2'].isna(),'Product_Category_2']=0

In [83]:
dataf.loc[dataf['Product_Category_3'].isna(),'Product_Category_3']=0

In [87]:
dataf['Product_Category_3'].unique()

array([ 0., 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [90]:
dataf['Product_Category']=dataf['Product_Category_1']+dataf['Product_Category_2'].astype(int)+dataf['Product_Category_3'].astype(int)

In [106]:
dataf[dataf['Product_ID']=='P00000142']

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Source,Product_Category
293,1000049,P00000142,M,18-25,12,C,4+,1,3,4.0,5.0,13353.0,train,12
1066,1000181,P00000142,M,18-25,17,C,1,0,3,4.0,5.0,5396.0,train,12
1073,1000182,P00000142,M,18-25,4,C,0,0,3,4.0,5.0,13301.0,train,12
1322,1000215,P00000142,M,36-45,14,C,1,1,3,4.0,5.0,10620.0,train,12
1910,1000306,P00000142,M,18-25,0,C,3,0,3,4.0,5.0,8297.0,train,12
2805,1000453,P00000142,M,18-25,4,B,1,0,3,4.0,5.0,8276.0,train,12
3014,1000490,P00000142,M,0-17,10,B,1,0,3,4.0,5.0,10868.0,train,12
3551,1000574,P00000142,M,26-35,19,C,4+,1,3,4.0,5.0,10954.0,train,12
3742,1000613,P00000142,M,36-45,20,C,1,1,3,4.0,5.0,13610.0,train,12
5226,1000855,P00000142,F,18-25,2,A,2,1,3,4.0,5.0,10783.0,train,12
5316,1000869,P00000142,M,18-25,20,A,4+,1,3,4.0,5.0,13650.0,train,12
5882,1000954,P00000142,F,26-35,0,B,1,1,3,4.0,5.0,10915.0,train,12
6854,1001097,P00000142,M,18-25,17,A,4+,0,3,4.0,5.0,10596.0,train,12
7383,1001151,P00000142,M,26-35,15,C,2,1,3,4.0,5.0,10782.0,train,12
8489,1001301,P00000142,F,26-35,2,C,1,1,3,4.0,5.0,10931.0,train,12
9913,1001507,P00000142,M,36-45,17,C,0,0,3,4.0,5.0,13355.0,train,12
10875,1001666,P00000142,M,26-35,14,B,3,0,3,4.0,5.0,11012.0,train,12
11224,1001694,P00000142,M,26-35,12,B,3,1,3,4.0,5.0,8315.0,train,12
11521,1001737,P00000142,M,36-45,20,B,3,0,3,4.0,5.0,13348.0,train,12
11724,1001758,P00000142,F,26-35,0,B,1,0,3,4.0,5.0,10617.0,train,12
11922,1001790,P00000142,M,26-35,0,C,1,0,3,4.0,5.0,8029.0,train,12
12105,1001825,P00000142,M,26-35,7,C,4+,1,3,4.0,5.0,10920.0,train,12
12937,1001941,P00000142,M,36-45,17,A,1,0,3,4.0,5.0,13704.0,train,12
13370,1001996,P00000142,M,36-45,0,C,3,0,3,4.0,5.0,13279.0,train,12
13725,1002042,P00000142,M,0-17,10,C,4+,0,3,4.0,5.0,11020.0,train,12
14294,1002110,P00000142,M,51-55,11,C,3,0,3,4.0,5.0,8026.0,train,12
14660,1002173,P00000142,M,51-55,13,C,1,0,3,4.0,5.0,13616.0,train,12
14848,1002202,P00000142,F,0-17,10,C,2,0,3,4.0,5.0,8207.0,train,12
15191,1002260,P00000142,F,26-35,20,C,1,0,3,4.0,5.0,7914.0,train,12
15341,1002288,P00000142,M,0-17,10,B,2,0,3,4.0,5.0,8120.0,train,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772011,1000314,P00000142,F,55+,9,C,1,0,3,4.0,5.0,NaN,test,12
772722,1001335,P00000142,M,36-45,0,C,1,0,3,4.0,5.0,NaN,test,12
773155,1001882,P00000142,M,36-45,16,C,4+,0,3,4.0,5.0,NaN,test,12
773647,1002683,P00000142,M,36-45,7,C,1,1,3,4.0,5.0,NaN,test,12
773780,1002887,P00000142,M,26-35,3,B,3,1,3,4.0,5.0,NaN,test,12
774165,1003447,P00000142,M,26-35,12,B,0,0,3,4.0,5.0,NaN,test,12
774509,1003868,P00000142,M,18-25,12,C,0,0,3,4.0,5.0,NaN,test,12
775021,1004561,P00000142,F,26-35,9,C,2,1,3,4.0,5.0,NaN,test,12
775439,1005312,P00000142,M,26-35,1,A,1,0,3,4.0,5.0,NaN,test,12
775444,1005317,P00000142,F,26-35,0,A,1,0,3,4.0,5.0,NaN,test,12
775499,1005412,P00000142,M,26-35,12,A,3,0,3,4.0,5.0,NaN,test,12
775653,1005651,P00000142,F,26-35,6,B,4+,1,3,4.0,5.0,NaN,test,12
775783,1005824,P00000142,M,18-25,12,B,1,0,3,4.0,5.0,NaN,test,12
775954,1000019,P00000142,M,0-17,10,A,3,0,3,4.0,5.0,NaN,test,12
776422,1000840,P00000142,F,26-35,3,C,1,1,3,4.0,5.0,NaN,test,12
776457,1000899,P00000142,F,26-35,1,B,3,1,3,4.0,5.0,NaN,test,12
776623,1001142,P00000142,M,18-25,1,B,1,0,3,4.0,5.0,NaN,test,12
776719,1001276,P00000142,M,36-45,17,B,2,0,3,4.0,5.0,NaN,test,12
777222,1001993,P00000142,M,36-45,17,C,4+,1,3,4.0,5.0,NaN,test,12
777942,1003261,P00000142,M,46-50,20,B,1,1,3,4.0,5.0,NaN,test,12
778463,1003999,P00000142,M,36-45,17,B,4+,0,3,4.0,5.0,NaN,test,12
778705,1004347,P00000142,F,18-25,20,C,1,0,3,4.0,5.0,NaN,test,12
779346,1005322,P00000142,M,36-45,17,A,3,1,3,4.0,5.0,NaN,test,12
779625,1005730,P00000142,M,18-25,0,A,3,0,3,4.0,5.0,NaN,test,12
780862,1001655,P00000142,M,18-25,4,C,2,1,3,4.0,5.0,NaN,test,12
781853,1003285,P00000142,M,26-35,4,B,3,0,3,4.0,5.0,NaN,test,12
782295,1003859,P00000142,M,26-35,0,C,1,0,3,4.0,5.0,NaN,test,12
782386,1004005,P00000142,M,36-45,7,C,3,0,3,4.0,5.0,NaN,test,12
782948,1004939,P00000142,M,26-35,7,C,0,1,3,4.0,5.0,NaN,test,12
783383,1005583,P00000142,M,55+,15,B,2,1,3,4.0,5.0,NaN,test,12

In [108]:
dataf.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Source,Product_Category
0,1000001,P00069042,F,0-17,10,A,2,0,3,0.0,0.0,8370.0,train,3
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200.0,train,21
2,1000001,P00087842,F,0-17,10,A,2,0,12,0.0,0.0,1422.0,train,12
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,0.0,1057.0,train,26
4,1000002,P00285442,M,55+,16,C,4+,0,8,0.0,0.0,7969.0,train,8

In [109]:
dataf.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2                 0
Product_Category_3                 0
Purchase                      233599
Source                             0
Product_Category                   0
dtype: int64

In [111]:
dataf.drop(columns=['Product_Category_1','Product_Category_2','Product_Category_3'],axis=1,inplace=True)

In [113]:
dataf.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Purchase,Source,Product_Category
0,1000001,P00069042,F,0-17,10,A,2,0,8370.0,train,3
1,1000001,P00248942,F,0-17,10,A,2,0,15200.0,train,21
2,1000001,P00087842,F,0-17,10,A,2,0,1422.0,train,12
3,1000001,P00085442,F,0-17,10,A,2,0,1057.0,train,26
4,1000002,P00285442,M,55+,16,C,4+,0,7969.0,train,8

In [115]:
dataf.loc[:,'Occupation']=dataf['Occupation'].astype(object)

In [116]:
dataf.loc[:,'Marital_Status']=dataf['Marital_Status'].astype(object)

In [118]:
dataf.loc[:,'Product_Category']=dataf['Product_Category'].astype(object)

In [117]:
dataf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783667 entries, 0 to 783666
Data columns (total 11 columns):
User_ID                       783667 non-null int64
Product_ID                    783667 non-null object
Gender                        783667 non-null object
Age                           783667 non-null object
Occupation                    783667 non-null object
City_Category                 783667 non-null object
Stay_In_Current_City_Years    783667 non-null object
Marital_Status                783667 non-null object
Purchase                      550068 non-null float64
Source                        783667 non-null object
Product_Category              783667 non-null int64
dtypes: float64(1), int64(2), object(8)
memory usage: 65.8+ MB

In [125]:
data_column_category=dataf.select_dtypes(exclude=[np.number]).columns
data_column_category

Index(['Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Source',
       'Product_Category'],
      dtype='object')

In [126]:
data_column_Integer=dataf.columns.difference(data_column_category)
data_column_Integer

Index(['Purchase', 'User_ID'], dtype='object')

In [127]:
dataf[data_column_category].nunique()

Product_ID                    3677
Gender                           2
Age                              7
Occupation                      21
City_Category                    3
Stay_In_Current_City_Years       5
Marital_Status                   2
Source                           2
Product_Category                45
dtype: int64

In [128]:
dataf_one_hot=pd.get_dummies(dataf[data_column_category].drop(columns=['Product_ID','Source']))

In [129]:
dataf_one_hot.head()

,Gender_F,Gender_M,Age_0-17,Age_18-25,Age_26-35,Age_36-45,Age_46-50,Age_51-55,Age_55+,Occupation_0,...,Product_Category_36,Product_Category_37,Product_Category_38,Product_Category_39,Product_Category_40,Product_Category_41,Product_Category_42,Product_Category_43,Product_Category_44,Product_Category_48
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [130]:
data_model=pd.concat([dataf_one_hot,dataf['Product_ID'],dataf['Source'],dataf[data_column_Integer]],axis=1)

In [133]:
data_model.sort_index().head()

,Gender_F,Gender_M,Age_0-17,Age_18-25,Age_26-35,Age_36-45,Age_46-50,Age_51-55,Age_55+,Occupation_0,...,Product_Category_40,Product_Category_41,Product_Category_42,Product_Category_43,Product_Category_44,Product_Category_48,Product_ID,Source,Purchase,User_ID
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,P00069042,train,8370.0,1000001
1,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,P00248942,train,15200.0,1000001
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,P00087842,train,1422.0,1000001
3,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,P00085442,train,1057.0,1000001
4,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,P00285442,train,7969.0,1000002

In [134]:
X=data_model[data_model['Source']=='train'].drop(columns=['Product_ID','Source','Purchase','User_ID'])
Y=data_model[data_model['Source']=='train']['Purchase']

In [135]:
import sklearn.feature_selection
select=sklearn.feature_selection.SelectKBest(k=20)
selected_features=select.fit(X,Y)
indices_selected=selected_features.get_support(indices=True)
colnames_selected=[X.columns[i] for i in indices_selected]
colnames_selected

['Product_Category_5',
 'Product_Category_7',
 'Product_Category_8',
 'Product_Category_9',
 'Product_Category_10',
 'Product_Category_11',
 'Product_Category_12',
 'Product_Category_13',
 'Product_Category_14',
 'Product_Category_15',
 'Product_Category_16',
 'Product_Category_18',
 'Product_Category_19',
 'Product_Category_20',
 'Product_Category_26',
 'Product_Category_29',
 'Product_Category_41',
 'Product_Category_43',
 'Product_Category_44',
 'Product_Category_48']

In [137]:
train_modified=data_model[data_model['Source']=='train'].drop(columns=['Source'],axis=1)
#train_modified.drop(columns=['index'],inplace=True)
train_modified.shape

(550068, 88)

In [138]:
train_modified.head()

,Gender_F,Gender_M,Age_0-17,Age_18-25,Age_26-35,Age_36-45,Age_46-50,Age_51-55,Age_55+,Occupation_0,...,Product_Category_39,Product_Category_40,Product_Category_41,Product_Category_42,Product_Category_43,Product_Category_44,Product_Category_48,Product_ID,Purchase,User_ID
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,P00069042,8370.0,1000001
1,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,P00248942,15200.0,1000001
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,P00087842,1422.0,1000001
3,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,P00085442,1057.0,1000001
4,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,P00285442,7969.0,1000002

In [139]:
test_modified=data_model[data_model['Source']=='test'].drop(columns=['Source','Purchase'],axis=1)
#test_modified.drop(columns=['index'],inplace=True)
test_modified.shape

(233599, 87)

In [140]:
train_modified.to_csv("train_ready_for_model.csv",index=False)

In [141]:
test_modified.to_csv("test_ready_for_model.csv",index=False)

In [142]:
test_modified.head()

,Gender_F,Gender_M,Age_0-17,Age_18-25,Age_26-35,Age_36-45,Age_46-50,Age_51-55,Age_55+,Occupation_0,...,Product_Category_38,Product_Category_39,Product_Category_40,Product_Category_41,Product_Category_42,Product_Category_43,Product_Category_44,Product_Category_48,Product_ID,User_ID
550068,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,P00128942,1000004
550069,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,P00113442,1000009
550070,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,P00288442,1000010
550071,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,P00145342,1000010
550072,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,P00053842,1000011