In [1]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline

In [2]:
train=pd.read_csv("Train_UWu5bXk.csv")
test=pd.read_csv("Test_u94Q5KV.csv")
sample_submit=pd.read_csv("SampleSubmission_TmnO39y.csv")

In [3]:
sample_submit.head()

  Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0           FDW58            OUT049                NaN
1           FDW14            OUT017                NaN
2           NCN55            OUT010                NaN
3           FDQ58            OUT017                NaN
4           FDY38            OUT027                NaN

In [4]:
train.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [5]:
test.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type'],
      dtype='object')

In [6]:
train.columns.difference(test.columns)

Index(['Item_Outlet_Sales'], dtype='object')

In [7]:
print("Train Shape",train.shape)
print("Test Shape",test.shape)

Train Shape (8523, 12)
Test Shape (5681, 11)

In [8]:
train["Source"]='train'
test["Source"]='test'

In [9]:
train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Source
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,train
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,train
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,train
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,train
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,train

In [10]:
dataf=pd.concat([train,test],axis=0,sort=False)

In [11]:
dataf.reset_index(inplace=True)

In [12]:
dataf.index.sort_values()

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            14194, 14195, 14196, 14197, 14198, 14199, 14200, 14201, 14202,
            14203],
           dtype='int64', length=14204)

In [13]:
dataf.isna().sum()

index                           0
Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
Source                          0
dtype: int64

In [14]:
dataf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 14 columns):
index                        14204 non-null int64
Item_Identifier              14204 non-null object
Item_Weight                  11765 non-null float64
Item_Fat_Content             14204 non-null object
Item_Visibility              14204 non-null float64
Item_Type                    14204 non-null object
Item_MRP                     14204 non-null float64
Outlet_Identifier            14204 non-null object
Outlet_Establishment_Year    14204 non-null int64
Outlet_Size                  10188 non-null object
Outlet_Location_Type         14204 non-null object
Outlet_Type                  14204 non-null object
Item_Outlet_Sales            8523 non-null float64
Source                       14204 non-null object
dtypes: float64(4), int64(2), object(8)
memory usage: 1.5+ MB

In [15]:
dataf.describe()

,index,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,14204.000000,11765.000000,14204.000000,14204.000000,14204.000000,8523.000000
mean,3692.660025,12.792854,0.065953,141.004977,1997.830681,2181.288914
std,2278.810408,4.652502,0.051459,62.086938,8.371664,1706.499616
min,0.000000,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,1775.000000,8.710000,0.027036,94.012000,1987.000000,834.247400
50%,3550.500000,12.600000,0.054021,142.247000,1999.000000,1794.331000
75%,5326.000000,16.750000,0.094037,185.855600,2004.000000,3101.296400
max,8522.000000,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [16]:
dataf.shape

(14204, 14)

In [17]:
dataf.nunique()

index                         8523
Item_Identifier               1559
Item_Weight                    415
Item_Fat_Content                 5
Item_Visibility              13006
Item_Type                       16
Item_MRP                      8052
Outlet_Identifier               10
Outlet_Establishment_Year        9
Outlet_Size                      3
Outlet_Location_Type             3
Outlet_Type                      4
Item_Outlet_Sales             3493
Source                           2
dtype: int64

In [18]:
dataf.isna().sum()

index                           0
Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
Source                          0
dtype: int64

In [19]:
import pandas_profiling

C:\ProgramData\Anaconda3\lib\site-packages\pandas_profiling\plot.py:15: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2666, in run_cell
    self.events.trigger('post_run_cell', result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\events.py", line 88, in trigger
    func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\pylab\backend_inline.py", line 160, in configure_once
    activate_matplotlib(backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 311, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 231, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1410, in use
    reload(sys.modules['matplotlib.backends'])
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use(BACKEND)

In [20]:
#pandas_profiling.ProfileReport(dataf)

In [21]:
dataf[dataf["Item_Weight"].isna()]

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Source
7,7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636,train
18,18,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680,train
21,21,FDW12,NaN,Regular,0.035400,Baking Goods,144.5444,OUT027,1985,Medium,Tier 3,Supermarket Type3,4064.0432,train
23,23,FDC37,NaN,Low Fat,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store,214.3876,train
29,29,FDC14,NaN,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362,train
36,36,FDV20,NaN,Regular,0.059512,Fruits and Vegetables,128.0678,OUT027,1985,Medium,Tier 3,Supermarket Type3,2797.6916,train
38,38,FDX10,NaN,Regular,0.123111,Snack Foods,36.9874,OUT027,1985,Medium,Tier 3,Supermarket Type3,388.1614,train
39,39,FDB34,NaN,Low Fat,0.026481,Snack Foods,87.6198,OUT027,1985,Medium,Tier 3,Supermarket Type3,2180.4950,train
49,49,FDS02,NaN,Regular,0.255395,Dairy,196.8794,OUT019,1985,Small,Tier 1,Grocery Store,780.3176,train
59,59,FDI26,NaN,Low Fat,0.061082,Canned,180.0344,OUT019,1985,Small,Tier 1,Grocery Store,892.1720,train
62,62,FDF09,NaN,Low Fat,0.012090,Fruits and Vegetables,38.2848,OUT027,1985,Medium,Tier 3,Supermarket Type3,484.7024,train
63,63,FDY40,NaN,Regular,0.150286,Frozen Foods,51.0692,OUT019,1985,Small,Tier 1,Grocery Store,147.8076,train
64,64,FDY45,NaN,Low Fat,0.026016,Snack Foods,255.8356,OUT027,1985,Medium,Tier 3,Supermarket Type3,2543.3560,train
77,77,FDN48,NaN,Low Fat,0.113720,Baking Goods,89.9804,OUT019,1985,Small,Tier 1,Grocery Store,643.1628,train
83,83,NCL18,NaN,Low Fat,0.293418,Household,194.6136,OUT019,1985,Small,Tier 1,Grocery Store,583.2408,train
84,84,FDR12,NaN,Regular,0.031382,Baking Goods,171.3764,OUT027,1985,Medium,Tier 3,Supermarket Type3,3091.9752,train
87,87,FDQ49,NaN,Regular,0.039058,Breakfast,155.9630,OUT027,1985,Medium,Tier 3,Supermarket Type3,3285.7230,train
95,95,FDU04,NaN,Low Fat,0.009715,Frozen Foods,120.0414,OUT019,1985,Small,Tier 1,Grocery Store,487.3656,train
98,98,NCP18,NaN,Low Fat,0.028460,Household,149.9708,OUT027,1985,Medium,Tier 3,Supermarket Type3,4363.6532,train
101,101,FDD10,NaN,Regular,0.045798,Snack Foods,178.5344,OUT027,1985,Medium,Tier 3,Supermarket Type3,2854.9504,train
108,108,DRE60,NaN,low fat,0.278974,Soft Drinks,225.3720,OUT019,1985,Small,Tier 1,Grocery Store,679.1160,train
112,112,FDW39,NaN,Regular,0.064625,Meat,176.9370,OUT019,1985,Small,Tier 1,Grocery Store,176.4370,train
113,113,FDX34,NaN,Low Fat,0.071637,Snack Foods,121.7098,OUT027,1985,Medium,Tier 3,Supermarket Type3,4097.3332,train
130,130,FDY25,NaN,Low Fat,0.033810,Canned,180.5976,OUT027,1985,Medium,Tier 3,Supermarket Type3,7968.2944,train
132,132,NCR53,NaN,Low Fat,0.144338,Health and Hygiene,224.4404,OUT027,1985,Medium,Tier 3,Supermarket Type3,6976.2524,train
136,136,FDH35,NaN,Low Fat,0.059957,Starchy Foods,165.4526,OUT027,1985,Medium,Tier 3,Supermarket Type3,5262.4832,train
153,153,DRK12,NaN,Low Fat,0.041683,Soft Drinks,31.2900,OUT027,1985,Medium,Tier 3,Supermarket Type3,898.8300,train
161,161,FDR07,NaN,Low Fat,0.077367,Fruits and Vegetables,97.0094,OUT027,1985,Medium,Tier 3,Supermarket Type3,1808.9786,train
168,168,NCB30,NaN,Low Fat,0.025579,Household,198.8084,OUT027,1985,Medium,Tier 3,Supermarket Type3,5555.4352,train
178,178,DRY23,NaN,Regular,0.191014,Soft Drinks,42.1112,OUT019,1985,Small,Tier 1,Grocery Store,42.6112,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14001,5478,FDV14,NaN,Low Fat,0.077909,Dairy,87.1856,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14005,5482,FDO39,NaN,Regular,0.240512,Meat,181.9608,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14008,5485,FDH46,NaN,Regular,0.041082,Snack Foods,100.5332,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14022,5499,FDG26,NaN,Low Fat,0.074674,Canned,257.8330,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14040,5517,DRO35,NaN,Low Fat,0.034403,Hard Drinks,117.7492,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14042,5519,FDY43,NaN,Low Fat,0.000000,Fruits and Vegetables,169.2474,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14049,5526,FDW33,NaN,Low Fat,0.098641,Snack Foods,104.7280,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14055,5532,FDP44,NaN,Regular,0.079328,Fruits and Vegetables,102.7332,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14069,5546,FDL45,NaN,Low Fat,0.065987,Snack Foods,126.6704,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14086,5563,NCN05,NaN,LF,0.014390,Health and Hygiene,184.7950,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14089,5566,FDW47,NaN,LF,0.046151,Breads,123.8414,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14090,5567,FDT51,NaN,Regular,0.010866,Meat,111.4544,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14106,5583,NCG18,NaN,Low Fat,0.040231,Household,101.2332,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14116,5593,FDU22,NaN,Low Fat,0.092845,Snack Foods,116.8124,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14119,5596,FDJ15,NaN,Regular,0.040835,Dairy,185.0608,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14123,5600,FDA07,NaN,Regular,0.054180,Fruits and Vegetables,123.5072,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14132,5609,FDP28,NaN,Regular,0.080250,Frozen Foods,259.4936,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14138,5615,FDF04,NaN,Low Fat,0.013571,Frozen Foods,258.5304,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14148,5625,FDQ44,NaN,Low Fat,0.035965,Fruits and Vegetables,121.1756,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14149,5626,FDL50,NaN,Regular,0.042108,Canned,125.5046,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14150,5627,FDW57,NaN,Regular,0.115117,Snack Foods,178.6028,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14157,5634,NCV42,NaN,Low Fat,0.031270,Household,110.1228,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14163,5640,FDI60,NaN,Regular,0.038136,Baking Goods,62.8510,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14166,5643,FDQ19,NaN,Regular,0.000000,Fruits and Vegetables,244.3512,OUT019,1985,Small,Tier 1,Grocery Store,NaN,test
14171,5648,FDK26,NaN,Regular,0.000000,Canned,187.5240,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14178,5655,FDX32,NaN,Regular,0.099375,Fruits and Vegetables,143.6786,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14179,5656,FDC39,NaN,Low Fat,0.158425,Dairy,207.8296,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14184,5661,DRG37,NaN,Low Fat,0.000000,Soft Drinks,155.7972,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14188,5665,DRE03,NaN,Low Fat,0.024110,Dairy,46.0718,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
14192,5669,FDN31,NaN,Low Fat,0.072529,Fruits and Vegetables,188.0530,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test

In [22]:
dataf[dataf["Item_Identifier"]=='NCL18']

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Source
83,83,NCL18,NaN,Low Fat,0.293418,Household,194.6136,OUT019,1985,Small,Tier 1,Grocery Store,583.2408,train
658,658,NCL18,18.85,Low Fat,0.167444,Household,194.6136,OUT013,1987,High,Tier 3,Supermarket Type1,1166.4816,train
1592,1592,NCL18,18.85,Low Fat,0.167844,Household,193.9136,OUT049,1999,Medium,Tier 1,Supermarket Type1,3110.6176,train
2548,2548,NCL18,18.85,Low Fat,0.167584,Household,194.6136,OUT046,1997,Small,Tier 1,Supermarket Type1,2721.7904,train
4056,4056,NCL18,18.85,Low Fat,0.168267,Household,195.5136,OUT018,2009,Medium,Tier 3,Supermarket Type2,1749.7224,train
4421,4421,NCL18,18.85,Low Fat,0.168532,Household,192.5136,OUT017,2007,NaN,Tier 2,Supermarket Type1,2916.2040,train
6973,6973,NCL18,18.85,Low Fat,0.167552,Household,193.1136,OUT035,2004,Small,Tier 2,Supermarket Type1,2332.9632,train
9493,970,NCL18,NaN,Low Fat,0.166772,Household,193.0136,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
11781,3258,NCL18,18.85,Low Fat,0.167924,Household,193.7136,OUT045,2002,NaN,Tier 2,Supermarket Type1,NaN,test

In [23]:
dataf["Item_Weight"]=dataf.groupby("Item_Identifier").Item_Weight.transform(lambda x:x.fillna(x.mean()))

In [24]:
dataf[dataf["Item_Identifier"]=='NCL18']

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Source
83,83,NCL18,18.85,Low Fat,0.293418,Household,194.6136,OUT019,1985,Small,Tier 1,Grocery Store,583.2408,train
658,658,NCL18,18.85,Low Fat,0.167444,Household,194.6136,OUT013,1987,High,Tier 3,Supermarket Type1,1166.4816,train
1592,1592,NCL18,18.85,Low Fat,0.167844,Household,193.9136,OUT049,1999,Medium,Tier 1,Supermarket Type1,3110.6176,train
2548,2548,NCL18,18.85,Low Fat,0.167584,Household,194.6136,OUT046,1997,Small,Tier 1,Supermarket Type1,2721.7904,train
4056,4056,NCL18,18.85,Low Fat,0.168267,Household,195.5136,OUT018,2009,Medium,Tier 3,Supermarket Type2,1749.7224,train
4421,4421,NCL18,18.85,Low Fat,0.168532,Household,192.5136,OUT017,2007,NaN,Tier 2,Supermarket Type1,2916.2040,train
6973,6973,NCL18,18.85,Low Fat,0.167552,Household,193.1136,OUT035,2004,Small,Tier 2,Supermarket Type1,2332.9632,train
9493,970,NCL18,18.85,Low Fat,0.166772,Household,193.0136,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN,test
11781,3258,NCL18,18.85,Low Fat,0.167924,Household,193.7136,OUT045,2002,NaN,Tier 2,Supermarket Type1,NaN,test

In [25]:
dataf.isna().sum()

index                           0
Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
Source                          0
dtype: int64

In [26]:
dataf.index.sort_values()

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            14194, 14195, 14196, 14197, 14198, 14199, 14200, 14201, 14202,
            14203],
           dtype='int64', length=14204)

In [27]:
def  applymode(x):
    a=x.mode()[0]
    return x.fillna(a)

In [28]:
dataf["Outlet_Size"]=dataf.groupby("Outlet_Type").Outlet_Size.transform(applymode)

In [29]:
dataf.Outlet_Size.value_counts()

Small     7996
Medium    4655
High      1553
Name: Outlet_Size, dtype: int64

In [30]:
dataf.isna().sum()

index                           0
Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
Source                          0
dtype: int64

In [31]:
import numpy as np
dataf.loc[dataf.Item_Visibility ==0.000000,'Item_Visibility']=np.NaN

In [32]:
dataf.isna().sum()

index                           0
Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility               879
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
Source                          0
dtype: int64

In [33]:
dataf["Item_Visibility"]=dataf.groupby("Item_Identifier").Item_Visibility.transform(lambda x:x.fillna(x.mean()))

In [34]:
dataf.isna().sum()

index                           0
Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
Source                          0
dtype: int64

In [35]:
dataf['Item_Fat_Content'].value_counts()

Low Fat    8485
Regular    4824
LF          522
reg         195
low fat     178
Name: Item_Fat_Content, dtype: int64

In [36]:
'''
dataf.loc[dataf['Item_Fat_Content']=='LF','Item_Fat_Content']='Low Fat'
dataf.loc[dataf['Item_Fat_Content']=='low fat','Item_Fat_Content']='Low Fat'
dataf.loc[dataf['Item_Fat_Content']=='reg','Item_Fat_Content']='Regular'
'''

"\ndataf.loc[dataf['Item_Fat_Content']=='LF','Item_Fat_Content']='Low Fat'\ndataf.loc[dataf['Item_Fat_Content']=='low fat','Item_Fat_Content']='Low Fat'\ndataf.loc[dataf['Item_Fat_Content']=='reg','Item_Fat_Content']='Regular'\n"

In [37]:
## Easiest way of replacing each values from a single command
dataf['Item_Fat_Content']=dataf.Item_Fat_Content.replace({'LF':'Low Fat','reg':'Regular','low fat':'Low Fat'})

In [38]:
dataf['Item_Fat_Content'].value_counts()

Low Fat    9185
Regular    5019
Name: Item_Fat_Content, dtype: int64

In [39]:
dataf['Outlet_Total_Years']=2018-dataf['Outlet_Establishment_Year']

In [40]:
dataf.drop(columns=["Outlet_Establishment_Year"],inplace=True)

In [41]:
dataf.head()

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Source,Outlet_Total_Years
0,0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,Medium,Tier 1,Supermarket Type1,3735.1380,train,19
1,1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,Medium,Tier 3,Supermarket Type2,443.4228,train,9
2,2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,Medium,Tier 1,Supermarket Type1,2097.2700,train,19
3,3,FDX07,19.20,Regular,0.022930,Fruits and Vegetables,182.0950,OUT010,Small,Tier 3,Grocery Store,732.3800,train,20
4,4,NCD19,8.93,Low Fat,0.014670,Household,53.8614,OUT013,High,Tier 3,Supermarket Type1,994.7052,train,31

In [42]:
dataf["Item_Identifier_Pattern"]=dataf["Item_Identifier"].apply(lambda x:x[0:2])

In [43]:
#pandas_profiling.ProfileReport(dataf)

In [44]:
dataf.Outlet_Type.value_counts()

Supermarket Type1    9294
Grocery Store        1805
Supermarket Type3    1559
Supermarket Type2    1546
Name: Outlet_Type, dtype: int64

In [45]:
dataf.loc[dataf.Outlet_Type.str.startswith('Supermarket Type'),'Outlet_Type_Pattern']='SuperMarket'

In [46]:
dataf.loc[dataf.Outlet_Type.str.startswith('Grocery'),'Outlet_Type_Pattern']='Grocery'

In [47]:
dataf.Outlet_Type_Pattern.value_counts()

SuperMarket    12399
Grocery         1805
Name: Outlet_Type_Pattern, dtype: int64

In [48]:
#dataf.drop(columns=["Outlet_Type"],inplace=True)

In [49]:
dataf.groupby(["Outlet_Type_Pattern","Outlet_Size"])["Item_Identifier"].count()

Outlet_Type_Pattern  Outlet_Size
Grocery              Small          1805
SuperMarket          High           1553
                     Medium         4655
                     Small          6191
Name: Item_Identifier, dtype: int64

In [50]:
dataf.groupby(['Outlet_Type_Pattern','Outlet_Size']).count()

                                 index  Item_Identifier  Item_Weight  \
Outlet_Type_Pattern Outlet_Size
Grocery             Small         1805             1805         1805
SuperMarket         High          1553             1553         1553
                    Medium        4655             4655         4655
                    Small         6191             6191         6191

                                 Item_Fat_Content  Item_Visibility  Item_Type  \
Outlet_Type_Pattern Outlet_Size
Grocery             Small                    1805             1805       1805
SuperMarket         High                     1553             1553       1553
                    Medium                   4655             4655       4655
                    Small                    6191             6191       6191

                                 Item_MRP  Outlet_Identifier  \
Outlet_Type_Pattern Outlet_Size
Grocery             Small            1805               1805
SuperMarket         High             1553               1553
                    Medium           4655               4655
                    Small            6191               6191

                                 Outlet_Location_Type  Outlet_Type  \
Outlet_Type_Pattern Outlet_Size
Grocery             Small                        1805         1805
SuperMarket         High                         1553         1553
                    Medium                       4655         4655
                    Small                        6191         6191

                                 Item_Outlet_Sales  Source  \
Outlet_Type_Pattern Outlet_Size
Grocery             Small                     1083    1805
SuperMarket         High                       932    1553
                    Medium                    2793    4655
                    Small                     3715    6191

                                 Outlet_Total_Years  Item_Identifier_Pattern
Outlet_Type_Pattern Outlet_Size
Grocery             Small                      1805                     1805
SuperMarket         High                       1553                     1553
                    Medium                     4655                     4655
                    Small                      6191                     6191

In [51]:
data_column_category=dataf.select_dtypes(exclude=[np.number]).columns
data_column_category

Index(['Item_Identifier', 'Item_Fat_Content', 'Item_Type', 'Outlet_Identifier',
       'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type', 'Source',
       'Item_Identifier_Pattern', 'Outlet_Type_Pattern'],
      dtype='object')

In [53]:
data_column_Integer=dataf.columns.difference(data_column_category)
data_column_Integer

Index(['Item_MRP', 'Item_Outlet_Sales', 'Item_Visibility', 'Item_Weight',
       'Outlet_Total_Years', 'index'],
      dtype='object')

In [54]:
dataf[data_column_category].nunique()

Item_Identifier            1559
Item_Fat_Content              2
Item_Type                    16
Outlet_Identifier            10
Outlet_Size                   3
Outlet_Location_Type          3
Outlet_Type                   4
Source                        2
Item_Identifier_Pattern       3
Outlet_Type_Pattern           2
dtype: int64

In [55]:
dataf_one_hot=pd.get_dummies(dataf[data_column_category].drop(columns=['Item_Identifier','Source']))

In [56]:
data_model=pd.concat([dataf_one_hot,dataf['Item_Identifier'],dataf['Outlet_Identifier'],dataf[data_column_Integer],dataf['Source']],axis=1)

In [57]:
data_model.isna().sum()

Item_Fat_Content_Low Fat              0
Item_Fat_Content_Regular              0
Item_Type_Baking Goods                0
Item_Type_Breads                      0
Item_Type_Breakfast                   0
Item_Type_Canned                      0
Item_Type_Dairy                       0
Item_Type_Frozen Foods                0
Item_Type_Fruits and Vegetables       0
Item_Type_Hard Drinks                 0
Item_Type_Health and Hygiene          0
Item_Type_Household                   0
Item_Type_Meat                        0
Item_Type_Others                      0
Item_Type_Seafood                     0
Item_Type_Snack Foods                 0
Item_Type_Soft Drinks                 0
Item_Type_Starchy Foods               0
Outlet_Identifier_OUT010              0
Outlet_Identifier_OUT013              0
Outlet_Identifier_OUT017              0
Outlet_Identifier_OUT018              0
Outlet_Identifier_OUT019              0
Outlet_Identifier_OUT027              0
Outlet_Identifier_OUT035              0
Outlet_Identifier_OUT045              0
Outlet_Identifier_OUT046              0
Outlet_Identifier_OUT049              0
Outlet_Size_High                      0
Outlet_Size_Medium                    0
Outlet_Size_Small                     0
Outlet_Location_Type_Tier 1           0
Outlet_Location_Type_Tier 2           0
Outlet_Location_Type_Tier 3           0
Outlet_Type_Grocery Store             0
Outlet_Type_Supermarket Type1         0
Outlet_Type_Supermarket Type2         0
Outlet_Type_Supermarket Type3         0
Item_Identifier_Pattern_DR            0
Item_Identifier_Pattern_FD            0
Item_Identifier_Pattern_NC            0
Outlet_Type_Pattern_Grocery           0
Outlet_Type_Pattern_SuperMarket       0
Item_Identifier                       0
Outlet_Identifier                     0
Item_MRP                              0
Item_Outlet_Sales                  5681
Item_Visibility                       0
Item_Weight                           0
Outlet_Total_Years                    0
index                                 0
Source                                0
dtype: int64

In [58]:
from itertools import combinations
from sklearn.preprocessing import PolynomialFeatures

def add_interactions(df):
    combos=list(combinations(list(df.columns),2))
    #combos3=list(combinations(list(df.columns),3))
    #combos4=list(combinations(list(df.columns),4))
    #combos5=list(combinations(list(df.columns),5))
    #combos6=list(combinations(list(df.columns),6))
    colnames=list(df.columns)+['_'.join(x[:5]) for x in combos]#+['_'.join(x[:5]) for x in combos3]+['_'.join(x[:5]) for x in combos4]+['_'.join(x[:5]) for x in combos5]+['_'.join(x[:5]) for x in combos6]
    poly=PolynomialFeatures(degree=2,interaction_only=True,include_bias=False)
    df=poly.fit_transform(df)
    df=pd.DataFrame(df)
    df.columns=colnames
    noint_indices=[i for i,x in enumerate(list((df==0).all())) if x]
    df=df.drop(df.columns[noint_indices],axis=1)
    return df

def add_interactions(df):
    combos=list(combinations(list(df.columns),2))
    colnames=list(df.columns)+['_'.join(x) for x in combos]
    poly=PolynomialFeatures(interaction_only=True,include_bias=False)
    df=poly.fit_transform(df)
    df=pd.DataFrame(df)
    df.columns=colnames
    noint_indices=[i for i,x in enumerate(list((df==0).all())) if x]
    df=df.drop(df.columns[noint_indices],axis=1)
    return df

In [59]:
from itertools import combinations
from sklearn.preprocessing import PolynomialFeatures

def add_interactions(df):
    combos=list(combinations(list(df.columns),2))
    #combos3=list(combinations(list(df.columns),3))
    #combos4=list(combinations(list(df.columns),4))
    #combos5=list(combinations(list(df.columns),5))
    #combos6=list(combinations(list(df.columns),6))
    colnames=list(df.columns)+['_'.join(x[:5]) for x in combos]#+['_'.join(x[:5]) for x in combos3]+['_'.join(x[:5]) for x in combos4]+['_'.join(x[:5]) for x in combos5]+['_'.join(x[:5]) for x in combos6]
    poly=PolynomialFeatures(degree=2,interaction_only=True,include_bias=False)
    df=poly.fit_transform(df)
    df=pd.DataFrame(df)
    df.columns=colnames
    noint_indices=[i for i,x in enumerate(list((df==0).all())) if x]
    df=df.drop(df.columns[noint_indices],axis=1)
    return df

In [60]:
X.drop(columns='index',axis=1,inplace=True)

NameError: name 'X' is not defined

In [61]:
Y.loc[Y['Source']=='train','Source_ID']=1
Y.loc[Y['Source']=='test','Source_ID']=0

NameError: name 'Y' is not defined

In [62]:
col=['Outlet_Type_Pattern_SuperMarket_Item_MRP',
 'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
 'Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
 'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
 'Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP']
dx=X
dx.head()

NameError: name 'X' is not defined

dy=dx

combos2=list(combinations(list(dy.columns),2))
combos3=list(combinations(list(dy.columns),3))
print(len(combos2),len(combos3),len(dy.columns))

colnames=list(dy.columns)+['_'.join(x) for x in combos]
colnames


poly=PolynomialFeatures(degree=3,interaction_only=True,include_bias=False)
dy=poly.fit_transform(dy)
dy=pd.DataFrame(dy)
print(colnames)
dy.columns=colnames
noint_indices=[i for i,x in enumerate(list((dy==0).all())) if x]
dy=dy.drop(dy.columns[noint_indices],axis=1)

dy.head()

In [63]:
dx=add_interactions(dx)

NameError: name 'dx' is not defined

In [64]:
dx.head()

NameError: name 'dx' is not defined

In [65]:
dx.isna().sum()

NameError: name 'dx' is not defined

In [66]:
data_model.isna().sum()

Item_Fat_Content_Low Fat              0
Item_Fat_Content_Regular              0
Item_Type_Baking Goods                0
Item_Type_Breads                      0
Item_Type_Breakfast                   0
Item_Type_Canned                      0
Item_Type_Dairy                       0
Item_Type_Frozen Foods                0
Item_Type_Fruits and Vegetables       0
Item_Type_Hard Drinks                 0
Item_Type_Health and Hygiene          0
Item_Type_Household                   0
Item_Type_Meat                        0
Item_Type_Others                      0
Item_Type_Seafood                     0
Item_Type_Snack Foods                 0
Item_Type_Soft Drinks                 0
Item_Type_Starchy Foods               0
Outlet_Identifier_OUT010              0
Outlet_Identifier_OUT013              0
Outlet_Identifier_OUT017              0
Outlet_Identifier_OUT018              0
Outlet_Identifier_OUT019              0
Outlet_Identifier_OUT027              0
Outlet_Identifier_OUT035              0
Outlet_Identifier_OUT045              0
Outlet_Identifier_OUT046              0
Outlet_Identifier_OUT049              0
Outlet_Size_High                      0
Outlet_Size_Medium                    0
Outlet_Size_Small                     0
Outlet_Location_Type_Tier 1           0
Outlet_Location_Type_Tier 2           0
Outlet_Location_Type_Tier 3           0
Outlet_Type_Grocery Store             0
Outlet_Type_Supermarket Type1         0
Outlet_Type_Supermarket Type2         0
Outlet_Type_Supermarket Type3         0
Item_Identifier_Pattern_DR            0
Item_Identifier_Pattern_FD            0
Item_Identifier_Pattern_NC            0
Outlet_Type_Pattern_Grocery           0
Outlet_Type_Pattern_SuperMarket       0
Item_Identifier                       0
Outlet_Identifier                     0
Item_MRP                              0
Item_Outlet_Sales                  5681
Item_Visibility                       0
Item_Weight                           0
Outlet_Total_Years                    0
index                                 0
Source                                0
dtype: int64

In [151]:
col=list(data_model.columns)

In [152]:
data_model=pd.concat([data_model,dx],axis=1)#.drop(columns=col)

In [153]:
data_model.isna().sum()

Item_Fat_Content_Low Fat                                      0
Item_Fat_Content_Regular                                      0
Item_Type_Baking Goods                                        0
Item_Type_Breads                                              0
Item_Type_Breakfast                                           0
Item_Type_Canned                                              0
Item_Type_Dairy                                               0
Item_Type_Frozen Foods                                        0
Item_Type_Fruits and Vegetables                               0
Item_Type_Hard Drinks                                         0
Item_Type_Health and Hygiene                                  0
Item_Type_Household                                           0
Item_Type_Meat                                                0
Item_Type_Others                                              0
Item_Type_Seafood                                             0
Item_Type_Snack Foods                                         0
Item_Type_Soft Drinks                                         0
Item_Type_Starchy Foods                                       0
Outlet_Identifier_OUT010                                      0
Outlet_Identifier_OUT013                                      0
Outlet_Identifier_OUT017                                      0
Outlet_Identifier_OUT018                                      0
Outlet_Identifier_OUT019                                      0
Outlet_Identifier_OUT027                                      0
Outlet_Identifier_OUT035                                      0
Outlet_Identifier_OUT045                                      0
Outlet_Identifier_OUT046                                      0
Outlet_Identifier_OUT049                                      0
Outlet_Size_High                                              0
Outlet_Size_Medium                                            0
                                                             ..
Item_Identifier_Pattern_DR_Item_MRP                           0
Item_Identifier_Pattern_DR_Item_Visibility                    0
Item_Identifier_Pattern_DR_Item_Weight                        0
Item_Identifier_Pattern_DR_Outlet_Total_Years                 0
Item_Identifier_Pattern_FD_Outlet_Type_Pattern_Grocery        0
Item_Identifier_Pattern_FD_Outlet_Type_Pattern_SuperMarket    0
Item_Identifier_Pattern_FD_Item_MRP                           0
Item_Identifier_Pattern_FD_Item_Visibility                    0
Item_Identifier_Pattern_FD_Item_Weight                        0
Item_Identifier_Pattern_FD_Outlet_Total_Years                 0
Item_Identifier_Pattern_NC_Outlet_Type_Pattern_Grocery        0
Item_Identifier_Pattern_NC_Outlet_Type_Pattern_SuperMarket    0
Item_Identifier_Pattern_NC_Item_MRP                           0
Item_Identifier_Pattern_NC_Item_Visibility                    0
Item_Identifier_Pattern_NC_Item_Weight                        0
Item_Identifier_Pattern_NC_Outlet_Total_Years                 0
Outlet_Type_Pattern_Grocery_Item_MRP                          0
Outlet_Type_Pattern_Grocery_Item_Visibility                   0
Outlet_Type_Pattern_Grocery_Item_Weight                       0
Outlet_Type_Pattern_Grocery_Outlet_Total_Years                0
Outlet_Type_Pattern_SuperMarket_Item_MRP                      0
Outlet_Type_Pattern_SuperMarket_Item_Visibility               0
Outlet_Type_Pattern_SuperMarket_Item_Weight                   0
Outlet_Type_Pattern_SuperMarket_Outlet_Total_Years            0
Item_MRP_Item_Visibility                                      0
Item_MRP_Item_Weight                                          0
Item_MRP_Outlet_Total_Years                                   0
Item_Visibility_Item_Weight                                   0
Item_Visibility_Outlet_Total_Years                            0
Item_Weight_Outlet_Total_Years                                0
Length: 829, dtype: int64

from sklearn.decomposition import PCA
pca=PCA(n_components=20)
x_pca=pd.DataFrame(pca.fit_transform(X))

x_pca.head()

Y.loc[Y['Item_Outlet_Sales'].isna(),'Item_Outlet_Sales']=Y['Item_Outlet_Sales'].mean()

Y.isna().sum()

x_train=X[X['Source_ID']==1.0]
y_train=Y[Y['']]

import sklearn.feature_selection
select=sklearn.feature_selection.SelectKBest(k=35)
selected_features=select.fit(X,Y['Item_Outlet_Sales'])
indices_selected=selected_features.get_support(indices=True)
colnames_selected=[X.columns[i] for i in indices_selected]
tr_sel=X[colnames_selected]
colnames_selected

df=pd.concat([tr_sel,data_model[['Item_Identifier','Outlet_Identifier','Source','Item_Outlet_Sales']]],axis=1)

df.loc[df['Source']=='test','Item_Outlet_Sales']=np.NaN

train_modified=df[df['Source']=='train'].drop(columns=['Source'])
train_modified.shape

In [154]:
#pandas_profiling.ProfileReport(data_model)

In [155]:
X=data_model[data_model['Source']=='train'].drop(columns=['Item_Identifier','Source','Outlet_Identifier','Item_Outlet_Sales','Outlet_Type_Grocery Store'])
Y=data_model[data_model['Source']=='train']['Item_Outlet_Sales']

In [156]:
import sklearn.feature_selection
select=sklearn.feature_selection.SelectKBest(k=10)
selected_features=select.fit(X,Y)
indices_selected=selected_features.get_support(indices=True)
colnames_selected=[X.columns[i] for i in indices_selected]
colnames_selected

['Outlet_Type_Pattern_Grocery',
 'Outlet_Type_Pattern_SuperMarket',
 'Item_MRP',
 'Outlet_Type_Pattern_Grocery',
 'Outlet_Type_Pattern_SuperMarket',
 'Item_MRP',
 'Outlet_Size_Small_Outlet_Type_Pattern_Grocery',
 'Outlet_Type_Pattern_Grocery_Item_Weight',
 'Outlet_Type_Pattern_Grocery_Outlet_Total_Years',
 'Outlet_Type_Pattern_SuperMarket_Item_MRP']

data_modified=pd.concat([data_model[colnames_selected],data_model[['Item_Identifier','Outlet_Identifier','Source']]],axis=1)
data_modified.info()

In [449]:
train_modified=data_model[data_model['Source']=='train'].drop(columns=['Source'],axis=1)
train_modified.drop(columns=['index'],inplace=True)
train_modified.shape

(8523, 659)

In [450]:
#pandas_profiling.ProfileReport(train_modified)

In [451]:
train_modified.head()

,Item_Fat_Content_Low Fat,Item_Fat_Content_Regular,Item_Type_Baking Goods,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,Item_Type_Fruits and Vegetables,Item_Type_Hard Drinks,...,Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP
0,1,0,0,0,0,0,1,0,0,0,...,62404.636405,1.558925e+07,62404.636405,1.558925e+07,1.558925e+07,62404.636405,1.558925e+07,1.558925e+07,3.894339e+09,1.558925e+07
1,0,1,0,0,0,0,0,0,0,0,...,2329.915669,1.124632e+05,2329.915669,1.124632e+05,1.124632e+05,2329.915669,1.124632e+05,1.124632e+05,5.428507e+06,1.124632e+05
2,1,0,0,0,0,0,0,0,0,0,...,20055.657924,2.840242e+06,20055.657924,2.840242e+06,2.840242e+06,20055.657924,2.840242e+06,2.840242e+06,4.022294e+08,2.840242e+06
3,0,1,0,0,0,0,0,0,1,0,...,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,1,0,0,0,0,0,0,0,0,0,...,2901.050410,1.562546e+05,2901.050410,1.562546e+05,1.562546e+05,2901.050410,1.562546e+05,1.562546e+05,8.416093e+06,1.562546e+05

test_modified=df[df['Source']=='test'].drop(columns=['Item_Outlet_Sales','Source'])
test_modified

In [452]:
test_modified=data_model[data_model['Source']=='test'].drop(columns=['Source','Item_Outlet_Sales'],axis=1)
test_modified.drop(columns=['index'],inplace=True)
test_modified.shape

(5681, 658)

In [453]:
train_modified.columns

Index(['Item_Fat_Content_Low Fat', 'Item_Fat_Content_Regular',
       'Item_Type_Baking Goods', 'Item_Type_Breads', 'Item_Type_Breakfast',
       'Item_Type_Canned', 'Item_Type_Dairy', 'Item_Type_Frozen Foods',
       'Item_Type_Fruits and Vegetables', 'Item_Type_Hard Drinks',
       ...
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP'],
      dtype='object', length=659)

In [454]:
test_modified.columns

Index(['Item_Fat_Content_Low Fat', 'Item_Fat_Content_Regular',
       'Item_Type_Baking Goods', 'Item_Type_Breads', 'Item_Type_Breakfast',
       'Item_Type_Canned', 'Item_Type_Dairy', 'Item_Type_Frozen Foods',
       'Item_Type_Fruits and Vegetables', 'Item_Type_Hard Drinks',
       ...
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP',
       'Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP'],
      dtype='object', length=658)

In [455]:
train_modified.to_csv("train_ready_for_model.csv",index=False)

In [456]:
test_modified.to_csv("test_ready_for_model.csv",index=False)

In [457]:
test_modified.head()

,Item_Fat_Content_Low Fat,Item_Fat_Content_Regular,Item_Type_Baking Goods,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,Item_Type_Fruits and Vegetables,Item_Type_Hard Drinks,...,Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP,Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP,Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP_Outlet_Type_Pattern_SuperMarket_Item_MRP
8523,1,0,0,0,0,0,0,0,0,0,...,11634.254189,1.254896e+06,11634.254189,1.254896e+06,1.254896e+06,11634.254189,1.254896e+06,1.254896e+06,1.353559e+08,1.254896e+06
8524,0,1,0,0,0,0,1,0,0,0,...,7624.747472,6.657914e+05,7624.747472,6.657914e+05,6.657914e+05,7624.747472,6.657914e+05,6.657914e+05,5.813677e+07,6.657914e+05
8525,1,0,0,0,0,0,0,0,0,0,...,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
8526,1,0,0,0,0,0,0,0,0,0,...,24035.541156,3.726326e+06,24035.541156,3.726326e+06,3.726326e+06,24035.541156,3.726326e+06,3.726326e+06,5.777072e+08,3.726326e+06
8527,0,1,0,0,0,0,1,0,0,0,...,54863.692900,1.285072e+07,54863.692900,1.285072e+07,1.285072e+07,54863.692900,1.285072e+07,1.285072e+07,3.010025e+09,1.285072e+07