In [1]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline

In [2]:
train=pd.read_csv("train.csv")
hist=pd.read_csv("historical_user_logs.csv")
test=pd.read_csv("test.csv")
sample_submit=pd.read_csv("sample_submission_2s8l9nF.csv")

In [3]:
train.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
0,140690,2017-07-02 00:00,858557,C,359520,13787,4,NaN,10.0,Female,4.0,3.0,3.0,0,0
1,333291,2017-07-02 00:00,243253,C,105960,11085,5,NaN,8.0,Female,2.0,2.0,NaN,0,0
2,129781,2017-07-02 00:00,243253,C,359520,13787,4,NaN,8.0,Female,2.0,2.0,NaN,0,0
3,464848,2017-07-02 00:00,1097446,I,359520,13787,3,NaN,3.0,Male,3.0,3.0,2.0,1,0
4,90569,2017-07-02 00:01,663656,C,405490,60305,3,NaN,2.0,Male,2.0,3.0,2.0,1,0

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463291 entries, 0 to 463290
Data columns (total 15 columns):
session_id                463291 non-null int64
DateTime                  463291 non-null object
user_id                   463291 non-null int64
product                   463291 non-null object
campaign_id               463291 non-null int64
webpage_id                463291 non-null int64
product_category_1        463291 non-null int64
product_category_2        97437 non-null float64
user_group_id             445048 non-null float64
gender                    445048 non-null object
age_level                 445048 non-null float64
user_depth                445048 non-null float64
city_development_index    338162 non-null float64
var_1                     463291 non-null int64
is_click                  463291 non-null int64
dtypes: float64(5), int64(7), object(3)
memory usage: 53.0+ MB

In [5]:
hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24287534 entries, 0 to 24287533
Data columns (total 4 columns):
DateTime    object
user_id     int64
product     object
action      object
dtypes: int64(1), object(3)
memory usage: 741.2+ MB

train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [157]:
df=pd.concat([train,test],axis=0,sort=False)
df.reset_index(inplace=True)
df.drop(columns='index',inplace=True)

In [158]:
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
0,140690,2017-07-02 00:00,858557,C,359520,13787,4,NaN,10.0,Female,4.0,3.0,3.0,0,0.0
1,333291,2017-07-02 00:00,243253,C,105960,11085,5,NaN,8.0,Female,2.0,2.0,NaN,0,0.0
2,129781,2017-07-02 00:00,243253,C,359520,13787,4,NaN,8.0,Female,2.0,2.0,NaN,0,0.0
3,464848,2017-07-02 00:00,1097446,I,359520,13787,3,NaN,3.0,Male,3.0,3.0,2.0,1,0.0
4,90569,2017-07-02 00:01,663656,C,405490,60305,3,NaN,2.0,Male,2.0,3.0,2.0,1,0.0

In [159]:
df[df.is_click==1.0].groupby(['product','product_category_1']).size()

product  product_category_1
A        1                      299
         2                      557
         3                       15
         4                       82
B        1                      113
         2                     1013
         3                       31
         4                       81
C        1                      300
         2                      283
         3                     6405
         4                     2635
         5                     1683
D        1                      225
         2                      260
         3                       48
         4                     1998
         5                      418
E        1                      799
         2                      675
F        1                       71
         2                       88
         3                      183
         5                        2
G        1                      109
         2                       25
         3                       18
         4                      201
         5                       82
H        1                      889
         2                      393
         3                     2621
         4                     2049
         5                     1702
I        1                     2102
         2                      976
         3                      185
         4                      809
         5                        7
J        1                      899
dtype: int64

In [161]:
import pandas_profiling
pandas_profiling.ProfileReport(df)

C:\ProgramData\Anaconda3\lib\site-packages\pandas_profiling\plot.py:15: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2666, in run_cell
    self.events.trigger('post_run_cell', result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\events.py", line 88, in trigger
    func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\pylab\backend_inline.py", line 160, in configure_once
    activate_matplotlib(backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 311, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 231, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1410, in use
    reload(sys.modules['matplotlib.backends'])
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use(BACKEND)

In [9]:
df.shape[0]

592149

In [10]:
df.groupby('is_click').size()

is_click
0.0    431960
1.0     31331
dtype: int64

In [11]:
df['DateTime']=pd.to_datetime(df.DateTime)

In [12]:
df.shape

(592149, 15)

In [13]:
df[df.is_click==1.0].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31331 entries, 38 to 463256
Data columns (total 15 columns):
session_id                31331 non-null int64
DateTime                  31331 non-null datetime64[ns]
user_id                   31331 non-null int64
product                   31331 non-null object
campaign_id               31331 non-null int64
webpage_id                31331 non-null int64
product_category_1        31331 non-null int64
product_category_2        6186 non-null float64
user_group_id             30057 non-null float64
gender                    30057 non-null object
age_level                 30057 non-null float64
user_depth                30057 non-null float64
city_development_index    22849 non-null float64
var_1                     31331 non-null int64
is_click                  31331 non-null float64
dtypes: datetime64[ns](1), float64(6), int64(6), object(2)
memory usage: 3.8+ MB

In [14]:
df.product_category_1.nunique()

5

In [15]:
df.groupby(['product_category_1','product']).size()

product_category_1  product
1                   A           6259
                    B           3717
                    C           6257
                    D           5012
                    E          13131
                    F           1965
                    G           2463
                    H          19510
                    I          31525
                    J          12148
2                   A          10873
                    B          20046
                    C           4446
                    D           5966
                    E          13808
                    F           1928
                    G            749
                    H           6537
                    I          17654
                    J              3
3                   A            284
                    B           2212
                    C          82110
                    D           4335
                    F           3906
                    G            489
                    H          34789
                    I           5190
4                   A           2553
                    B           3285
                    C          56737
                    D          36891
                    F             14
                    G           4999
                    H          38969
                    I          21607
5                   B              1
                    C          41638
                    D           8774
                    F            533
                    G           3725
                    H          54649
                    I            462
dtype: int64

In [16]:
df.loc[df.product_category_2.isna(),'product_category_2']=999999.

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le = LabelEncoder()
le.fit(df['product_category_2'].unique())
df.loc[:,'product_category_2']=le.transform(df['product_category_2'])

In [19]:
df['product_category_2'].unique()

array([31, 18,  6, 13, 23, 30,  0, 14, 25,  9, 26,  1, 11,  5, 10, 20,  4,
       28, 15, 17,  8,  2, 27, 19, 29,  3, 21, 24,  7, 12, 22, 16],
      dtype=int64)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592149 entries, 0 to 592148
Data columns (total 15 columns):
session_id                592149 non-null int64
DateTime                  592149 non-null datetime64[ns]
user_id                   592149 non-null int64
product                   592149 non-null object
campaign_id               592149 non-null int64
webpage_id                592149 non-null int64
product_category_1        592149 non-null int64
product_category_2        592149 non-null int64
user_group_id             568222 non-null float64
gender                    568222 non-null object
age_level                 568222 non-null float64
user_depth                568222 non-null float64
city_development_index    432411 non-null float64
var_1                     592149 non-null int64
is_click                  463291 non-null float64
dtypes: datetime64[ns](1), float64(5), int64(7), object(2)
memory usage: 67.8+ MB

In [21]:
a=df.user_group_id.mode()
df.loc[df.user_group_id.isna(),'user_group_id']=a[0]

In [22]:
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
0,140690,2017-07-02 00:00:00,858557,C,359520,13787,4,31,10.0,Female,4.0,3.0,3.0,0,0.0
1,333291,2017-07-02 00:00:00,243253,C,105960,11085,5,31,8.0,Female,2.0,2.0,NaN,0,0.0
2,129781,2017-07-02 00:00:00,243253,C,359520,13787,4,31,8.0,Female,2.0,2.0,NaN,0,0.0
3,464848,2017-07-02 00:00:00,1097446,I,359520,13787,3,31,3.0,Male,3.0,3.0,2.0,1,0.0
4,90569,2017-07-02 00:01:00,663656,C,405490,60305,3,31,2.0,Male,2.0,3.0,2.0,1,0.0

In [23]:
df.user_group_id.unique()

array([10.,  8.,  3.,  2.,  1.,  9.,  4., 11.,  7.,  5., 12.,  6.,  0.])

In [24]:
df.gender.unique()

array(['Female', 'Male', nan], dtype=object)

In [25]:
a=df.gender.mode()
a[0]

'Male'

In [26]:
df.loc[df.gender.isna(),'gender']=df.gender.mode()[0]

In [27]:
le2 = LabelEncoder()
le2.fit(df.gender)
df.loc[:,'gender']=le2.transform(df['gender'])

In [28]:
le2.classes_

array(['Female', 'Male'], dtype=object)

In [29]:
df.gender.unique()

array([0, 1], dtype=int64)

In [30]:
df.age_level.unique()

array([ 4.,  2.,  3.,  1., nan,  5.,  6.,  0.])

In [31]:
df.loc[df.age_level.isna(),'age_level']=df.age_level.mode()[0]

In [32]:
df.age_level.unique()

array([4., 2., 3., 1., 5., 6., 0.])

In [33]:
df.user_depth.unique()

array([ 3.,  2., nan,  1.])

In [34]:
df.loc[df.user_depth.isna(),'user_depth']=df.user_depth.mode()[0]

In [35]:
df.city_development_index.unique()

array([ 3., nan,  2.,  4.,  1.])

In [36]:
df.loc[df.city_development_index.isna(),'city_development_index']=df.city_development_index.mode()[0]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592149 entries, 0 to 592148
Data columns (total 15 columns):
session_id                592149 non-null int64
DateTime                  592149 non-null datetime64[ns]
user_id                   592149 non-null int64
product                   592149 non-null object
campaign_id               592149 non-null int64
webpage_id                592149 non-null int64
product_category_1        592149 non-null int64
product_category_2        592149 non-null int64
user_group_id             592149 non-null float64
gender                    592149 non-null int64
age_level                 592149 non-null float64
user_depth                592149 non-null float64
city_development_index    592149 non-null float64
var_1                     592149 non-null int64
is_click                  463291 non-null float64
dtypes: datetime64[ns](1), float64(5), int64(8), object(1)
memory usage: 67.8+ MB

In [38]:
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
0,140690,2017-07-02 00:00:00,858557,C,359520,13787,4,31,10.0,0,4.0,3.0,3.0,0,0.0
1,333291,2017-07-02 00:00:00,243253,C,105960,11085,5,31,8.0,0,2.0,2.0,2.0,0,0.0
2,129781,2017-07-02 00:00:00,243253,C,359520,13787,4,31,8.0,0,2.0,2.0,2.0,0,0.0
3,464848,2017-07-02 00:00:00,1097446,I,359520,13787,3,31,3.0,1,3.0,3.0,2.0,1,0.0
4,90569,2017-07-02 00:01:00,663656,C,405490,60305,3,31,2.0,1,2.0,3.0,2.0,1,0.0

In [39]:
#hist=pd.read_csv("historical_user_logs.csv")

In [40]:
prod=df.groupby(['product','product_category_1']).size().to_frame('size').reset_index()
prod.drop(columns='size',inplace=True)
prod.head()

  product  product_category_1
0       A                   1
1       A                   2
2       A                   3
3       A                   4
4       B                   1

In [41]:
up_met=hist[hist.action=='view'].groupby(['user_id','product']).size().to_frame('size').reset_index()
up_met.rename(columns={'size':'pc_view_count'}, inplace=True)
up_met.head()

   user_id product  pc_view_count
0        4       A              3
1        4       B              1
2        4       H              1
3        4       I              2
4       19       A             14

In [42]:
up_met_temp=hist[hist.action=='interest'].groupby(['user_id','product']).size().to_frame('size').reset_index()
up_met_temp.rename(columns={'size':'pc_interest_count'}, inplace=True) 
up_met_temp.head()

   user_id product  pc_interest_count
0       19       D                  1
1       19       F                  2
2       19       G                  2
3       26       H                  1
4       30       H                  1

In [43]:
up_met=pd.merge(up_met,up_met_temp,how='left',on=['user_id','product'])
up_met.head()

   user_id product  pc_view_count  pc_interest_count
0        4       A              3                NaN
1        4       B              1                NaN
2        4       H              1                NaN
3        4       I              2                NaN
4       19       A             14                NaN

In [44]:
up_met=pd.merge(up_met,prod,how='left',on=['product'])
up_met.head()

   user_id product  pc_view_count  pc_interest_count  product_category_1
0        4       A              3                NaN                   1
1        4       A              3                NaN                   2
2        4       A              3                NaN                   3
3        4       A              3                NaN                   4
4        4       B              1                NaN                   1

In [45]:
up_met=up_met.groupby(['user_id','product_category_1'])[['pc_view_count','pc_interest_count']].sum().reset_index()
up_met.loc[up_met.pc_view_count.isna(),'pc_view_count']=0.0
up_met.loc[up_met.pc_interest_count.isna(),'pc_interest_count']=0.0
up_met.head()

   user_id  product_category_1  pc_view_count  pc_interest_count
0        4                   1            7.0                0.0
1        4                   2            7.0                0.0
2        4                   3            7.0                0.0
3        4                   4            7.0                0.0
4        4                   5            4.0                0.0

In [46]:
df=pd.merge(df,up_met,how='left',on=['user_id','product_category_1'])
df.loc[df.pc_view_count.isna(),'pc_view_count']=0.0
df.loc[df.pc_interest_count.isna(),'pc_interest_count']=0.0
df['pc_action_count']=df['pc_view_count']+df['pc_interest_count']
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click,pc_view_count,pc_interest_count,pc_action_count
0,140690,2017-07-02 00:00:00,858557,C,359520,13787,4,31,10.0,0,4.0,3.0,3.0,0,0.0,191.0,0.0,191.0
1,333291,2017-07-02 00:00:00,243253,C,105960,11085,5,31,8.0,0,2.0,2.0,2.0,0,0.0,62.0,0.0,62.0
2,129781,2017-07-02 00:00:00,243253,C,359520,13787,4,31,8.0,0,2.0,2.0,2.0,0,0.0,62.0,0.0,62.0
3,464848,2017-07-02 00:00:00,1097446,I,359520,13787,3,31,3.0,1,3.0,3.0,2.0,1,0.0,41.0,2.0,43.0
4,90569,2017-07-02 00:01:00,663656,C,405490,60305,3,31,2.0,1,2.0,3.0,2.0,1,0.0,57.0,3.0,60.0

In [47]:
hist.head()

           DateTime  user_id product action
0  2017-05-28 15:44      704       B   view
1  2017-05-29 07:08   499679       F   view
2  2017-05-29 07:10   499679       G   view
3  2017-05-29 07:10   499679       G   view
4  2017-05-29 07:10   499679       G   view

In [48]:
hist.action.unique()

array(['view', 'interest'], dtype=object)

In [49]:
hist['DateTime']=pd.to_datetime(hist.DateTime)
hist['Weekday_name']=hist.DateTime.dt.weekday_name
hist.loc[(hist.DateTime.dt.weekday_name.isin(['Saturday','Sunday'])),'Weekseason']='Weekend'
hist.loc[hist.Weekseason.isna(),'Weekseason']='Weekday'
hist.loc[(5<=hist.DateTime.dt.hour) & (hist.DateTime.dt.hour<12),'Timegroup']='Morning'
hist.loc[(12<=hist.DateTime.dt.hour) & (hist.DateTime.dt.hour<17),'Timegroup']='Afternoon'
hist.loc[(17<=hist.DateTime.dt.hour) & (hist.DateTime.dt.hour<21),'Timegroup']='Evening'
hist.loc[hist.Timegroup.isna(),'Timegroup']='Night'

In [50]:
hist.head()

,DateTime,user_id,product,action,Weekday_name,Weekseason,Timegroup
0,2017-05-28 15:44:00,704,B,view,Sunday,Weekend,Afternoon
1,2017-05-29 07:08:00,499679,F,view,Monday,Weekday,Morning
2,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning
3,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning
4,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning

In [51]:
hist_met=hist.groupby(['user_id','product']).size().to_frame('size').reset_index()

In [52]:
hist_met.drop(columns=['size'],inplace=True)

for act in hist['action'].unique():
    hist_temp=hist[(hist['action']==act)].groupby(['user_id','product']).size().to_frame('size').reset_index()
    colnm='total_'+act+'_count'
    hist_temp.rename(columns={'size':colnm}, inplace=True)
    hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product'])

In [53]:
hist_met.head()

   user_id product
0        4       A
1        4       B
2        4       H
3        4       I
4       19       A

for wd in hist['Weekseason'].unique():
    for act in hist['action'].unique():
        hist_temp=hist[(hist['Weekseason']==wd) & (hist['action']==act)].groupby(['user_id','product']).size().to_frame('size').reset_index()
        colnm=wd+'_'+act+'_count'
        hist_temp.rename(columns={'size':colnm}, inplace=True)
        hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product'])

In [54]:
hist_met.head()

   user_id product
0        4       A
1        4       B
2        4       H
3        4       I
4       19       A

hist_met['Weekend_count']=hist_met['Weekend_view_count']+hist_met['Weekend_interest_count']
hist_met['Weekday_count']=hist_met['Weekday_view_count']+hist_met['Weekday_interest_count']

for wd in hist['Weekday_name'].unique():
    for act in hist['action'].unique():
        hist_temp=hist[(hist['Weekday_name']==wd) & (hist['action']==act)].groupby(['user_id','product']).size().to_frame('size').reset_index()
        colnm=wd+'_'+act+'_count'
        hist_temp.rename(columns={'size':colnm}, inplace=True)
        hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product'])

for wd in hist['Weekday_name'].unique():
    hist_met[wd+'_count']=hist_met[wd+'_view_count']+hist_met[wd+'_interest_count']

In [55]:
hist_met.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035753 entries, 0 to 1035752
Data columns (total 2 columns):
user_id    1035753 non-null int64
product    1035753 non-null object
dtypes: int64(1), object(1)
memory usage: 15.8+ MB

for wd in hist['Timegroup'].unique():
    for act in hist['action'].unique():
        hist_temp=hist[(hist['Timegroup']==wd) & (hist['action']==act)].groupby(['user_id','product']).size().to_frame('size').reset_index()
        colnm=wd+'_'+act+'_count'
        hist_temp.rename(columns={'size':colnm}, inplace=True)
        hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product'])

for wd in hist['Timegroup'].unique():
    hist_met[wd+'_count']=hist_met[wd+'_view_count']+hist_met[wd+'_interest_count']

for td in hist['Weekday_name'].unique():
    for wd in hist['Timegroup'].unique():
        for act in hist['action'].unique():
            hist_temp=hist[(hist['Timegroup']==wd) & (hist['Timegroup']==wd) & (hist['action']==act)].groupby(['user_id','product']).size().to_frame('size').reset_index()
            colnm=td[:5]+wd[:5]+'_'+act+'_count'
            hist_temp.rename(columns={'size':colnm}, inplace=True)
            hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product'])

In [56]:
df.loc[(df.DateTime.dt.weekday_name.isin(['Saturday','Sunday'])),'Weekseason']='Weekend'
df.loc[df.Weekseason.isna(),'Weekseason']='Weekday'
df['Weekday_name']=df.DateTime.dt.weekday_name
df.loc[(5<=df.DateTime.dt.hour) & (df.DateTime.dt.hour<12),'Timegroup']='Morning'
df.loc[(12<=df.DateTime.dt.hour) & (df.DateTime.dt.hour<17),'Timegroup']='Afternoon'
df.loc[(17<=df.DateTime.dt.hour) & (df.DateTime.dt.hour<21),'Timegroup']='Evening'

In [57]:
df.loc[df.Timegroup.isna(),'Timegroup']='Night'

In [58]:
df[df.is_click==1].head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,...,user_depth,city_development_index,var_1,is_click,pc_view_count,pc_interest_count,pc_action_count,Weekseason,Weekday_name,Timegroup
38,489923,2017-07-02 00:05:00,929999,H,359520,13787,3,31,2.0,1,...,2.0,2.0,0,1.0,140.0,1.0,141.0,Weekend,Sunday,Night
54,419802,2017-07-02 00:07:00,740951,G,98970,6970,4,31,9.0,0,...,3.0,4.0,1,1.0,31.0,2.0,33.0,Weekend,Sunday,Night
65,145098,2017-07-02 00:08:00,1005580,C,359520,13787,4,31,3.0,1,...,3.0,2.0,0,1.0,68.0,0.0,68.0,Weekend,Sunday,Night
106,102183,2017-07-02 00:13:00,504394,C,405490,60305,3,31,2.0,1,...,3.0,2.0,0,1.0,279.0,7.0,286.0,Weekend,Sunday,Night
107,72843,2017-07-02 00:13:00,963568,C,405490,60305,3,31,2.0,1,...,3.0,3.0,1,1.0,276.0,8.0,284.0,Weekend,Sunday,Night

In [59]:
hist.head()

,DateTime,user_id,product,action,Weekday_name,Weekseason,Timegroup
0,2017-05-28 15:44:00,704,B,view,Sunday,Weekend,Afternoon
1,2017-05-29 07:08:00,499679,F,view,Monday,Weekday,Morning
2,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning
3,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning
4,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning

In [60]:
#hist.drop(columns='Weekday_name',inplace=True)

In [61]:
hist.head()

,DateTime,user_id,product,action,Weekday_name,Weekseason,Timegroup
0,2017-05-28 15:44:00,704,B,view,Sunday,Weekend,Afternoon
1,2017-05-29 07:08:00,499679,F,view,Monday,Weekday,Morning
2,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning
3,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning
4,2017-05-29 07:10:00,499679,G,view,Monday,Weekday,Morning

In [62]:
hist_met=hist[(hist['action']=='view')].groupby(['user_id','product','Weekseason','Weekday_name','Timegroup']).size().to_frame('size').reset_index()
hist_met.rename(columns={'size':'day_view_count'}, inplace=True)

In [63]:
hist_met.head()

   user_id product Weekseason Weekday_name  Timegroup  day_view_count
0        4       A    Weekend     Saturday  Afternoon               3
1        4       B    Weekend     Saturday  Afternoon               1
2        4       H    Weekend     Saturday  Afternoon               1
3        4       I    Weekend     Saturday  Afternoon               2
4       19       A    Weekday     Thursday    Morning               2

In [64]:
hist_temp=hist[(hist['action']=='interest')].groupby(['user_id','product','Weekseason','Weekday_name','Timegroup']).size().to_frame('size').reset_index()
hist_temp.rename(columns={'size':'day_interest_count'}, inplace=True)
hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product','Weekseason','Weekday_name','Timegroup'])

In [65]:
hist_met.head()

,user_id,product,Weekseason,Weekday_name,Timegroup,day_view_count,day_interest_count
0,4,A,Weekend,Saturday,Afternoon,3,NaN
1,4,B,Weekend,Saturday,Afternoon,1,NaN
2,4,H,Weekend,Saturday,Afternoon,1,NaN
3,4,I,Weekend,Saturday,Afternoon,2,NaN
4,19,A,Weekday,Thursday,Morning,2,NaN

In [66]:
hist_temp=hist[(hist['action']=='view')].groupby(['user_id','product','Weekseason','Timegroup']).size().to_frame('size').reset_index()
hist_temp.rename(columns={'size':'weekseason_view_count'}, inplace=True)
hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product','Weekseason','Timegroup'])

In [67]:
hist_met.head()

,user_id,product,Weekseason,Weekday_name,Timegroup,day_view_count,day_interest_count,weekseason_view_count
0,4,A,Weekend,Saturday,Afternoon,3,NaN,3
1,4,B,Weekend,Saturday,Afternoon,1,NaN,1
2,4,H,Weekend,Saturday,Afternoon,1,NaN,1
3,4,I,Weekend,Saturday,Afternoon,2,NaN,2
4,19,A,Weekday,Thursday,Morning,2,NaN,2

In [68]:
hist_temp=hist[(hist['action']=='interest')].groupby(['user_id','product','Weekseason','Timegroup']).size().to_frame('size').reset_index()
hist_temp.rename(columns={'size':'weekseason_interest_count'}, inplace=True)
hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product','Weekseason','Timegroup'])

In [69]:
hist_temp=hist[(hist['action']=='view')].groupby(['user_id','product','Weekseason']).size().to_frame('size').reset_index()
hist_temp.rename(columns={'size':'tot_weekseason_view_count'}, inplace=True)
hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product','Weekseason'])

In [70]:
hist_temp=hist[(hist['action']=='interest')].groupby(['user_id','product','Weekseason']).size().to_frame('size').reset_index()
hist_temp.rename(columns={'size':'tot_weekseason_interest_count'}, inplace=True)
hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product','Weekseason'])

In [71]:
hist_temp=hist[(hist['action']=='view')].groupby(['user_id','product']).size().to_frame('size').reset_index()
hist_temp.rename(columns={'size':'total_view_count'}, inplace=True)
hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product'])

In [72]:
hist_temp=hist[(hist['action']=='interest')].groupby(['user_id','product']).size().to_frame('size').reset_index()
hist_temp.rename(columns={'size':'total_interest_count'}, inplace=True)
hist_met=pd.merge(hist_met,hist_temp,how='left',on=['user_id','product'])

In [84]:
hist_met.fillna(value=0,inplace=True)
hist_met.head()

,user_id,product,Weekseason,Weekday_name,Timegroup,day_view_count,day_interest_count,weekseason_view_count,weekseason_interest_count,tot_weekseason_view_count,tot_weekseason_interest_count,total_view_count,total_interest_count
0,4,A,Weekend,Saturday,Afternoon,3,0.0,3,0.0,3,0.0,3,0.0
1,4,B,Weekend,Saturday,Afternoon,1,0.0,1,0.0,1,0.0,1,0.0
2,4,H,Weekend,Saturday,Afternoon,1,0.0,1,0.0,1,0.0,1,0.0
3,4,I,Weekend,Saturday,Afternoon,2,0.0,2,0.0,2,0.0,2,0.0
4,19,A,Weekday,Thursday,Morning,2,0.0,2,0.0,8,0.0,14,0.0

In [85]:
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,...,user_depth,city_development_index,var_1,is_click,pc_view_count,pc_interest_count,pc_action_count,Weekseason,Weekday_name,Timegroup
0,140690,2017-07-02 00:00:00,858557,C,359520,13787,4,31,10.0,0,...,3.0,3.0,0,0.0,191.0,0.0,191.0,Weekend,Sunday,Night
1,333291,2017-07-02 00:00:00,243253,C,105960,11085,5,31,8.0,0,...,2.0,2.0,0,0.0,62.0,0.0,62.0,Weekend,Sunday,Night
2,129781,2017-07-02 00:00:00,243253,C,359520,13787,4,31,8.0,0,...,2.0,2.0,0,0.0,62.0,0.0,62.0,Weekend,Sunday,Night
3,464848,2017-07-02 00:00:00,1097446,I,359520,13787,3,31,3.0,1,...,3.0,2.0,1,0.0,41.0,2.0,43.0,Weekend,Sunday,Night
4,90569,2017-07-02 00:01:00,663656,C,405490,60305,3,31,2.0,1,...,3.0,2.0,1,0.0,57.0,3.0,60.0,Weekend,Sunday,Night

In [86]:
df_mod=pd.merge(df,hist_met,how='left',on=['user_id','product','Weekseason','Weekday_name','Timegroup'])

In [87]:
df_mod.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,...,Weekday_name,Timegroup,day_view_count,day_interest_count,weekseason_view_count,weekseason_interest_count,tot_weekseason_view_count,tot_weekseason_interest_count,total_view_count,total_interest_count
0,140690,2017-07-02 00:00:00,858557,C,359520,13787,4,31,10.0,0,...,Sunday,Night,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,333291,2017-07-02 00:00:00,243253,C,105960,11085,5,31,8.0,0,...,Sunday,Night,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,129781,2017-07-02 00:00:00,243253,C,359520,13787,4,31,8.0,0,...,Sunday,Night,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,464848,2017-07-02 00:00:00,1097446,I,359520,13787,3,31,3.0,1,...,Sunday,Night,1.0,0.0,1.0,0.0,1.0,0.0,8.0,1.0
4,90569,2017-07-02 00:01:00,663656,C,405490,60305,3,31,2.0,1,...,Sunday,Night,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
df_mod.isna().sum()

session_id                            0
DateTime                              0
user_id                               0
product                               0
campaign_id                           0
webpage_id                            0
product_category_1                    0
product_category_2                    0
user_group_id                         0
gender                                0
age_level                             0
user_depth                            0
city_development_index                0
var_1                                 0
is_click                         128858
pc_view_count                         0
pc_interest_count                     0
pc_action_count                       0
Weekseason                            0
Weekday_name                          0
Timegroup                             0
day_view_count                   491002
day_interest_count               491002
weekseason_view_count            491002
weekseason_interest_count        491002
tot_weekseason_view_count        491002
tot_weekseason_interest_count    491002
total_view_count                 491002
total_interest_count             491002
dtype: int64

In [97]:
for x in df_mod.columns:
    if (df_mod[x].isna().sum()>0) & (x not in ('is_click')):
        df_mod.loc[df_mod[x].isna(),x]=0

In [98]:
df_mod.isna().sum()

session_id                            0
DateTime                              0
user_id                               0
product                               0
campaign_id                           0
webpage_id                            0
product_category_1                    0
product_category_2                    0
user_group_id                         0
gender                                0
age_level                             0
user_depth                            0
city_development_index                0
var_1                                 0
is_click                         128858
pc_view_count                         0
pc_interest_count                     0
pc_action_count                       0
Weekseason                            0
Weekday_name                          0
Timegroup                             0
day_view_count                        0
day_interest_count                    0
weekseason_view_count                 0
weekseason_interest_count             0
tot_weekseason_view_count             0
tot_weekseason_interest_count         0
total_view_count                      0
total_interest_count                  0
dtype: int64

In [99]:
df_mod.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,...,Weekday_name,Timegroup,day_view_count,day_interest_count,weekseason_view_count,weekseason_interest_count,tot_weekseason_view_count,tot_weekseason_interest_count,total_view_count,total_interest_count
0,140690,2017-07-02 00:00:00,858557,C,359520,13787,4,31,10.0,0,...,Sunday,Night,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,333291,2017-07-02 00:00:00,243253,C,105960,11085,5,31,8.0,0,...,Sunday,Night,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,129781,2017-07-02 00:00:00,243253,C,359520,13787,4,31,8.0,0,...,Sunday,Night,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,464848,2017-07-02 00:00:00,1097446,I,359520,13787,3,31,3.0,1,...,Sunday,Night,1.0,0.0,1.0,0.0,1.0,0.0,8.0,1.0
4,90569,2017-07-02 00:01:00,663656,C,405490,60305,3,31,2.0,1,...,Sunday,Night,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [108]:
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 592149 entries, 0 to 592148
Data columns (total 28 columns):
session_id                       592149 non-null int64
user_id                          592149 non-null int64
product                          592149 non-null object
campaign_id                      592149 non-null int64
webpage_id                       592149 non-null int64
product_category_1               592149 non-null int64
product_category_2               592149 non-null int64
user_group_id                    592149 non-null float64
gender                           592149 non-null int64
age_level                        592149 non-null float64
user_depth                       592149 non-null float64
city_development_index           592149 non-null float64
var_1                            592149 non-null int64
is_click                         463291 non-null float64
pc_view_count                    592149 non-null float64
pc_interest_count                592149 non-null float64
pc_action_count                  592149 non-null float64
Weekseason                       592149 non-null object
Weekday_name                     592149 non-null object
Timegroup                        592149 non-null object
day_view_count                   592149 non-null float64
day_interest_count               592149 non-null float64
weekseason_view_count            592149 non-null float64
weekseason_interest_count        592149 non-null float64
tot_weekseason_view_count        592149 non-null float64
tot_weekseason_interest_count    592149 non-null float64
total_view_count                 592149 non-null float64
total_interest_count             592149 non-null float64
dtypes: float64(16), int64(8), object(4)
memory usage: 151.0+ MB

In [112]:
data_column_category=df_mod.select_dtypes(exclude=[np.number]).columns
data_column_category

Index(['product', 'Weekseason', 'Weekday_name', 'Timegroup'], dtype='object')

In [114]:
le3 = LabelEncoder()
le3.fit(df_mod['product'].unique())
df_mod.loc[:,'product']=le3.transform(df_mod['product'])

In [115]:
le4 = LabelEncoder()
le4.fit(df_mod['Weekseason'].unique())
df_mod.loc[:,'Weekseason']=le4.transform(df_mod['Weekseason'])

In [116]:
le5 = LabelEncoder()
le5.fit(df_mod['Weekday_name'].unique())
df_mod.loc[:,'Weekday_name']=le5.transform(df_mod['Weekday_name'])

In [117]:
le6 = LabelEncoder()
le6.fit(df_mod['Timegroup'].unique())
df_mod.loc[:,'Timegroup']=le6.transform(df_mod['Timegroup'])

In [201]:
#df_mod.drop(columns='index',inplace=True)

In [118]:
df_mod.head()

,session_id,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,...,Weekday_name,Timegroup,day_view_count,day_interest_count,weekseason_view_count,weekseason_interest_count,tot_weekseason_view_count,tot_weekseason_interest_count,total_view_count,total_interest_count
0,140690,858557,2,359520,13787,4,31,10.0,0,4.0,...,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,333291,243253,2,105960,11085,5,31,8.0,0,2.0,...,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,129781,243253,2,359520,13787,4,31,8.0,0,2.0,...,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,464848,1097446,8,359520,13787,3,31,3.0,1,3.0,...,3,3,1.0,0.0,1.0,0.0,1.0,0.0,8.0,1.0
4,90569,663656,2,405490,60305,3,31,2.0,1,2.0,...,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [203]:
for x in df_mod.columns:
    print(str(x)+'\t'+str(df_mod[x].nunique()))

session_id	592149
DateTime	11334
user_id	177729
product	10
campaign_id	10
webpage_id	9
product_category_1	5
product_category_2	32
user_group_id	14
gender	3
age_level	8
user_depth	4
city_development_index	5
var_1	2
is_click	2
pc_view_count	1860
pc_interest_count	82
Weekseason	2
Timegroup	4
Weekday_name	7
day_view_count	161
day_interest_count	13

In [204]:
df_mod.shape

(592149, 22)

In [136]:
df_mod.loc[df_mod.product_category_2!=31,'product_category_2']=1

In [137]:
df_mod.loc[df_mod.product_category_2==31,'product_category_2']=2

In [138]:
df_mod.head()

,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,...,pc_interest_count,pc_action_count,day_view_count,day_interest_count,weekseason_view_count,weekseason_interest_count,tot_weekseason_view_count,tot_weekseason_interest_count,total_view_count,total_interest_count
0,2,359520,13787,4,2,10.0,0,4.0,3.0,3.0,...,0.0,191.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,105960,11085,5,2,8.0,0,2.0,2.0,2.0,...,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,359520,13787,4,2,8.0,0,2.0,2.0,2.0,...,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8,359520,13787,3,2,3.0,1,3.0,3.0,2.0,...,2.0,43.0,1.0,0.0,1.0,0.0,1.0,0.0,8.0,1.0
4,2,405490,60305,3,2,2.0,1,2.0,3.0,2.0,...,3.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [139]:
for x in df_mod.columns:
    print(str(x)+'\t'+str(df_mod[x].nunique()))

product	10
campaign_id	10
webpage_id	9
product_category_1	5
product_category_2	2
user_group_id	13
gender	2
age_level	7
user_depth	3
city_development_index	4
var_1	2
Weekseason	2
Timegroup	4
Weekday_name	7
session_id	592149
user_id	177729
is_click	2
pc_view_count	1860
pc_interest_count	82
pc_action_count	1877
day_view_count	161
day_interest_count	13
weekseason_view_count	263
weekseason_interest_count	18
tot_weekseason_view_count	499
tot_weekseason_interest_count	29
total_view_count	618
total_interest_count	36

In [209]:
a=[x for x in df_mod.columns if x not in ('session_id','DateTime','pc_view_count','user_id','pc_interest_count','day_view_count','day_interest_count','is_click')]
for x in a:
    df_mod[x]=df_mod[x].astype(object)
b=[x for x in df_mod.columns if x in ('session_id','DateTime','pcview_count','user_id','pc_interest_count','is_click','day_view_count','day_interest_count')]

In [135]:
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 592149 entries, 0 to 592148
Data columns (total 28 columns):
product                          592149 non-null int64
campaign_id                      592149 non-null int64
webpage_id                       592149 non-null int64
product_category_1               592149 non-null int64
product_category_2               592149 non-null int64
user_group_id                    592149 non-null float64
gender                           592149 non-null int64
age_level                        592149 non-null float64
user_depth                       592149 non-null float64
city_development_index           592149 non-null float64
var_1                            592149 non-null int64
Weekseason                       592149 non-null int64
Timegroup                        592149 non-null int64
Weekday_name                     592149 non-null int64
session_id                       592149 non-null int64
user_id                          592149 non-null int64
is_click                         463291 non-null float64
pc_view_count                    592149 non-null float64
pc_interest_count                592149 non-null float64
pc_action_count                  592149 non-null float64
day_view_count                   592149 non-null float64
day_interest_count               592149 non-null float64
weekseason_view_count            592149 non-null float64
weekseason_interest_count        592149 non-null float64
tot_weekseason_view_count        592149 non-null float64
tot_weekseason_interest_count    592149 non-null float64
total_view_count                 592149 non-null float64
total_interest_count             592149 non-null float64
dtypes: float64(16), int64(12)
memory usage: 151.0 MB

In [146]:
a=['product',
 'campaign_id',
 'webpage_id',
 'product_category_1',
 'product_category_2',
 'user_group_id',
 'gender',
 'age_level',
 'user_depth',
 'city_development_index',
 'var_1',
 'Weekseason',
 'Timegroup',
 'Weekday_name']
b=[x for x in df_mod.columns if x not in a]
b=['session_id',
 'user_id',
 'is_click',
 'pc_view_count',
 'pc_interest_count',
 'pc_action_count',
 'day_view_count',
 'day_interest_count',
 'weekseason_view_count',
 'weekseason_interest_count',
 'tot_weekseason_view_count',
 'tot_weekseason_interest_count',
 'total_view_count',
 'total_interest_count']
for x in a:
    df_mod[x]=df_mod[x].astype(object)

In [147]:
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 592149 entries, 0 to 592148
Data columns (total 28 columns):
product                          592149 non-null object
campaign_id                      592149 non-null object
webpage_id                       592149 non-null object
product_category_1               592149 non-null object
product_category_2               592149 non-null object
user_group_id                    592149 non-null object
gender                           592149 non-null object
age_level                        592149 non-null object
user_depth                       592149 non-null object
city_development_index           592149 non-null object
var_1                            592149 non-null object
Weekseason                       592149 non-null object
Timegroup                        592149 non-null object
Weekday_name                     592149 non-null object
session_id                       592149 non-null int64
user_id                          592149 non-null int64
is_click                         463291 non-null float64
pc_view_count                    592149 non-null float64
pc_interest_count                592149 non-null float64
pc_action_count                  592149 non-null float64
day_view_count                   592149 non-null float64
day_interest_count               592149 non-null float64
weekseason_view_count            592149 non-null float64
weekseason_interest_count        592149 non-null float64
tot_weekseason_view_count        592149 non-null float64
tot_weekseason_interest_count    592149 non-null float64
total_view_count                 592149 non-null float64
total_interest_count             592149 non-null float64
dtypes: float64(12), int64(2), object(14)
memory usage: 151.0+ MB

In [148]:
dataf_one_hot=pd.get_dummies(df_mod[a])
dataf_one_hot.head()

,product_0,product_1,product_2,product_3,product_4,product_5,product_6,product_7,product_8,product_9,...,Timegroup_1,Timegroup_2,Timegroup_3,Weekday_name_0,Weekday_name_1,Weekday_name_2,Weekday_name_3,Weekday_name_4,Weekday_name_5,Weekday_name_6
0,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0

In [149]:
df_mod=pd.concat([dataf_one_hot,df_mod[b]],axis=1)

In [150]:
df_mod.columns

Index(['product_0', 'product_1', 'product_2', 'product_3', 'product_4',
       'product_5', 'product_6', 'product_7', 'product_8', 'product_9',
       'campaign_id_82320', 'campaign_id_98970', 'campaign_id_105960',
       'campaign_id_118601', 'campaign_id_359520', 'campaign_id_360936',
       'campaign_id_396664', 'campaign_id_404347', 'campaign_id_405490',
       'campaign_id_414149', 'webpage_id_1734', 'webpage_id_6970',
       'webpage_id_11085', 'webpage_id_13787', 'webpage_id_28529',
       'webpage_id_45962', 'webpage_id_51181', 'webpage_id_53587',
       'webpage_id_60305', 'product_category_1_1', 'product_category_1_2',
       'product_category_1_3', 'product_category_1_4', 'product_category_1_5',
       'product_category_2_1', 'product_category_2_2', 'user_group_id_0.0',
       'user_group_id_1.0', 'user_group_id_2.0', 'user_group_id_3.0',
       'user_group_id_4.0', 'user_group_id_5.0', 'user_group_id_6.0',
       'user_group_id_7.0', 'user_group_id_8.0', 'user_group_id_9.0',
       'user_group_id_10.0', 'user_group_id_11.0', 'user_group_id_12.0',
       'gender_0', 'gender_1', 'age_level_0.0', 'age_level_1.0',
       'age_level_2.0', 'age_level_3.0', 'age_level_4.0', 'age_level_5.0',
       'age_level_6.0', 'user_depth_1.0', 'user_depth_2.0', 'user_depth_3.0',
       'city_development_index_1.0', 'city_development_index_2.0',
       'city_development_index_3.0', 'city_development_index_4.0', 'var_1_0',
       'var_1_1', 'Weekseason_0', 'Weekseason_1', 'Timegroup_0', 'Timegroup_1',
       'Timegroup_2', 'Timegroup_3', 'Weekday_name_0', 'Weekday_name_1',
       'Weekday_name_2', 'Weekday_name_3', 'Weekday_name_4', 'Weekday_name_5',
       'Weekday_name_6', 'session_id', 'user_id', 'is_click', 'pc_view_count',
       'pc_interest_count', 'pc_action_count', 'day_view_count',
       'day_interest_count', 'weekseason_view_count',
       'weekseason_interest_count', 'tot_weekseason_view_count',
       'tot_weekseason_interest_count', 'total_view_count',
       'total_interest_count'],
      dtype='object')

In [100]:
#data_model[data_model.is_click==1]

In [101]:
#data_model.drop(columns=['DateTime'],inplace=True)
df_mod.drop(columns=['DateTime'],inplace=True)

In [102]:
#data_model.groupby('is_click').size()
df_mod.groupby('is_click').size()

is_click
0.0    431960
1.0     31331
dtype: int64

In [103]:
#data_model[data_model.is_click==1.0]

In [105]:
for x in df_mod.columns:
    print(x,df_mod[x].nunique())

session_id 592149
user_id 177729
product 10
campaign_id 10
webpage_id 9
product_category_1 5
product_category_2 32
user_group_id 13
gender 2
age_level 7
user_depth 3
city_development_index 4
var_1 2
is_click 2
pc_view_count 1860
pc_interest_count 82
pc_action_count 1877
Weekseason 2
Weekday_name 7
Timegroup 4
day_view_count 161
day_interest_count 13
weekseason_view_count 263
weekseason_interest_count 18
tot_weekseason_view_count 499
tot_weekseason_interest_count 29
total_view_count 618
total_interest_count 36

In [219]:
data_model.isna().sum()

product_A                          0
product_B                          0
product_C                          0
product_D                          0
product_E                          0
product_F                          0
product_G                          0
product_H                          0
product_I                          0
product_J                          0
campaign_id_82320                  0
campaign_id_98970                  0
campaign_id_105960                 0
campaign_id_118601                 0
campaign_id_359520                 0
campaign_id_360936                 0
campaign_id_396664                 0
campaign_id_404347                 0
campaign_id_405490                 0
campaign_id_414149                 0
webpage_id_1734                    0
webpage_id_6970                    0
webpage_id_11085                   0
webpage_id_13787                   0
webpage_id_28529                   0
webpage_id_45962                   0
webpage_id_51181                   0
webpage_id_53587                   0
webpage_id_60305                   0
product_category_1_1               0
                               ...
user_depth_1.0                     0
user_depth_2.0                     0
user_depth_3.0                     0
user_depth_4.0                     0
city_development_index_1.0         0
city_development_index_2.0         0
city_development_index_3.0         0
city_development_index_4.0         0
city_development_index_5.0         0
var_1_0                            0
var_1_1                            0
Weekseason_Weekday                 0
Weekseason_Weekend                 0
Timegroup_Afternoon                0
Timegroup_Evening                  0
Timegroup_Morning                  0
Timegroup_Night                    0
Weekday_name_Friday                0
Weekday_name_Monday                0
Weekday_name_Saturday              0
Weekday_name_Sunday                0
Weekday_name_Thursday              0
Weekday_name_Tuesday               0
Weekday_name_Wednesday             0
session_id                         0
user_id                            0
is_click                      128858
pc_interest_count                  0
day_view_count                     0
day_interest_count                 0
Length: 91, dtype: int64

X=data_model[data_model.is_click.notna()].drop(columns=['is_click','session_id'])
Y=data_model[data_model.is_click.notna()]['is_click']
X.head()

In [151]:
X=df_mod[df_mod.is_click.notna()].drop(columns=['is_click','session_id'])
Y=df_mod[df_mod.is_click.notna()]['is_click']
X.head()

,product_0,product_1,product_2,product_3,product_4,product_5,product_6,product_7,product_8,product_9,...,pc_interest_count,pc_action_count,day_view_count,day_interest_count,weekseason_view_count,weekseason_interest_count,tot_weekseason_view_count,tot_weekseason_interest_count,total_view_count,total_interest_count
0,0,0,1,0,0,0,0,0,0,0,...,0.0,191.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,1,0,0,0,0,0,0,0,...,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,1,0,0,0,0,0,0,0,...,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0,0,0,1,0,...,2.0,43.0,1.0,0.0,1.0,0.0,1.0,0.0,8.0,1.0
4,0,0,1,0,0,0,0,0,0,0,...,3.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [152]:
import sklearn.feature_selection
select=sklearn.feature_selection.SelectKBest(k=20)
selected_features=select.fit(X,Y)
indices_selected=selected_features.get_support(indices=True)
colnames_selected=[X.columns[i] for i in indices_selected]
colnames_selected

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:113: UserWarning: Features [75] are constant.
  UserWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:114: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

['product_1',
 'product_6',
 'product_9',
 'campaign_id_118601',
 'campaign_id_359520',
 'campaign_id_360936',
 'campaign_id_405490',
 'webpage_id_6970',
 'webpage_id_13787',
 'webpage_id_28529',
 'webpage_id_60305',
 'product_category_1_3',
 'product_category_1_4',
 'product_category_1_5',
 'user_group_id_4.0',
 'age_level_4.0',
 'var_1_0',
 'var_1_1',
 'Weekday_name_1',
 'Weekday_name_6']

In [153]:
train_modified=df_mod[df_mod.is_click.notna()]
#train_modified.drop(columns=['index'],inplace=True)
train_modified.shape

(463291, 94)

In [154]:
test_modified=df_mod[df_mod.is_click.isna()]
#train_modified.drop(columns=['index'],inplace=True)
test_modified.shape

(128858, 94)

In [155]:
train_modified.to_csv("train_ready_for_model.csv",index=False)

In [156]:
test_modified.to_csv("test_ready_for_model.csv",index=False)